### ISSUE TITLE
Maestro merges even if the PR reviewers have requested changes

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade-services#103]
Is there a way to tell the bot to hold-off merging a PR? I figured the "request changes" gesture in GitHub reviews would have been honored, but apparently not: https://github.com/aspnet/EntityFrameworkCore/pull/14506

![image](https://user-images.githubusercontent.com/2696087/51702381-8530d100-1fc8-11e9-9d85-ae43b59339ef.png)

**Comment by natemcmaster** [comment]
@markwilkie do we triage issues in this repo? Or should I move this to dotnet/arcade?

**Comment by mmitche** [comment]
@natemcmaster I'd move it to arcade.

**Comment by natemcmaster** [comment]
This issue was moved to dotnet/arcade#1999
