### ISSUE TITLE
Add dnceng to the Rollout Scorer

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2302]
We will be deploying various tools from the new repo. We probably want to add it to the Rollout Scorer

**Comment by tkapin** [comment]
I see the PR being merged, is there anything left to close this?

**Comment by missymessa** [comment]
It needs to be validated that it works before it should be closed.

**Comment by missymessa** [comment]
It worked! https://github.com/dotnet/dnceng/pull/185

Closing.
