### ISSUE TITLE
Deploy the Telemetry Service in the Helix cluster

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2303]
Currently, both Maestro and the Telemetry service are being deployed in the same cluster. This needs to be changed. 
We might want to create a new cluster to deploy the Telemetry service

### Release Note Category

- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Migrate the Telemetry service our of the Maestro SF cluster

**Comment by dkurepa** [comment]
We decided to migrate the TelemetryService into the Helix cluster. All other steps will remain the same

**Comment by dkurepa** [comment]
Pr that Migrates the staging and local dev environment: https://github.com/dotnet/dnceng/pull/373

**Comment by dkurepa** [comment]
The PR for the Staging environment has been merged. Logs show that the service is working as expected. Also, I killed the application instance running in the maestro cluster

**Comment by dkurepa** [comment]
The production PR has been merged. It should be rolled out this week. After he rollout, we should validate everything is working fine, and remove the Telemetry Application instance from the maestro SF cluster

**Comment by andriipatsula** [comment]
@dkurepa it was in the Rollout section. Do I need to close it and link to rollout PR? or it's not related

**Comment by dkurepa** [comment]
We reverted this, and will roll it out next week. I'll move it back to In Progress

**Comment by dkurepa** [comment]
The new PR has been merged. I will monitor the service after the deployment is completed

**Comment by dkurepa** [comment]
The PR has been rolled out and validated. The TelemetryApplication has been removed from the Maestro cluster
