### ISSUE TITLE
Deploy internal tools from the new dnceng repo

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2306]
We have successfully created the CI for the new dnceng repo. The next step is to make sure we can deploy to the staging environment from there. After we make sure we can, we need to create a good strategy for the first production rollout.
The biggest hurdle here is that we will have to disable/remove internal tooling rollouts from arcade-services before doing so.
I propose the following steps:
- [x] Validate staging deployments from the new repo
- [x] Disable internal tooling rollouts from arcade-services
- [x] Preform a rollout to production from the new repository, before rolling out arcade-services
- [ ] If the rollout fails from the new repo, re enable internal tooling rollouts in arcade-services and preform the rollout like usual

In the scenario above, we won't miss any rollouts, even if there's failure rolling out from the new repo.
We should also make sure that we notify our vendors and update the docs. These things are captured in https://github.com/dotnet/arcade-services/issues/2314.

**Comment by tkapin** [comment]
@dkurepa - Why is it blocked? What needs to happen to unblock this?

**Comment by dkurepa** [comment]
This issue was waiting for yesterdays rollout. Now that it has been completed, we can close it

**Comment by dkurepa** [comment]
We had successful rollouts from both repositories (arcade-services and dncegn). Think it's safe to say we can close this issue
