### ISSUE TITLE
Validation for Aracde-Services split

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade-services#2320]
List of things to validate before end of epic: 

- [x] Updated dependencies flow from builds of `dotnet/dnceng-shared` to `dotnet/arcade-services` and the repo builds successfully
- [x] Updated dependencies flow from builds of `dotnet/dnceng-shared` to `dotnet-helix-services` and the repo builds successfully
- [x] Updated dependencies flow from builds of `dotnet/dnceng-shared` to `dotnet/dnceng` and the repo builds successfully
- [x] `dotnet/dnceng` is able to deploy the suite of internal tools to staging
- [x] `dotnet/dnceng` is able to deploy the suite of internal tools to production
- [x] `dotnet/arcade-services` is able to deploy to staging
- [x] `dotnet/arcade-services` is able to deploy to production

**Comment by dkurepa** [comment]
@missymessa correct me if I'm wrong, but it looks like the helix-service part of this task is done. Will close the issue
