### ISSUE TITLE
The `arcade-services` internal CI build should not run unit tests

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2324]
We usually don't run tests in the main build again after they've been run in PR so I think we shouldn't run them in `arcade-services-official-ci` neither.

- They add 10+ minutes
- These tests [fail every now and then](https://dev.azure.com/dnceng/internal/_build/results?buildId=2124757&view=logs&j=a5c6a902-5556-5a70-4b67-7f49bfe8ebe3&t=30522ad2-fb1e-5545-250b-00b27148e543&s=6884a131-87da-5381-61f3-d7acc3b91d76)
- The reason these fail is because of the CodeCoverage tool loading some settings (this should be fixed too regardless)

### Release Note Description
Only run tests during PR builds

**Comment by dkurepa** [comment]
The PR has been merged. We will only run tests during PR builds now. This should reduce the noise we're getting in main builds because of flaky tests
