### ISSUE TITLE
Ensure build is ready to insert into VS

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2363]
Migrated from https://github.com/dotnet/core-eng/issues/13814

@markwilkie wrote:

From SDK team:
-  Check if any releases need insertion (10 workdays before ship date) or push for a insert ready build (13 - 10 workdays before ship date). Reference Shipping dates session. 
-  If there are build within "push for a insert ready build" period, but not ready. Investigate the reason and notify the team. Reference "push for a insert ready build". 
-  If insertion is needed. Make the insertion (5.0 branches does not need insertion) reference Insertion 

https://microsoft-:my.sharepoint.com/:x:/p/wul/ERRzj81D6eZEjUHQAL7UoLMBXFXcTBHD2dHMio4IPodpaw?e=yF9r0q

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

**Comment by premun** [comment]
Closing as per the last comment
