### ISSUE TITLE
Move inline script to ps1 script

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade-services#2377]
Inlined scripts are difficult to debug and *usually* not necessary.  The inlined script in Arcade's [eng/promote-build.yml](
https://github.com/dotnet/arcade/blob/master/eng/promote-build.yml#L76-L130) should be moved to a checked in script.  This inlined script is also, now in windowsdesktop and will need to be updated there.

@epananth

**Comment by premun** [comment]
This references a YAML that's no longer there, closing
