### ISSUE TITLE
Update 'branching' docs

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2382]
Migrated from https://github.com/dotnet/core-eng/issues/13312

@markwilkie wrote:

For each release, product teams need to branch.  While it's straight forward, @marcpopMSFT pointed out that he couldn't find a recipe (of sorts) for exactly how to do this.  Let's plug this doc gap.

Example from Marc:  https://teams.microsoft.com/l/message/19:1dad2081c8634f34915d88dce6220265@thread.skype/1621982824445?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1621982824445&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=Arcade&createdTime=1621982824445

cc/ @mmitche @rahulkotecha @adiaaida

**Comment by premun** [comment]
I think this is no longer relevant, we have the OneNote
