### ISSUE TITLE
[Needs Breakdown] Variable group checks & management

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2384]
Migrated from https://github.com/dotnet/core-eng/issues/9628

@jonfortescue wrote:

Specific case: https://github.com/dotnet/arcade/issues/4719

The issue described is essentially that secrets that were added to a variable group in dnceng were not added to the corresponding group in devdiv, which caused the builds that needed those secrets in devdiv to break. There were similar issues with service connections for publishing, etc.

I could imagine similar issues comparing secrets between subs, e.g. staging vs prod. In short, we need to have some story for verifying that our variable groups work as expected.

This is pretty high level so I'm tagging with breakdown so folks can consider specific needs & scenarios.

**Comment by premun** [comment]
We no longer really need variable groups because there's not many secrets left. Closing this one
