### ISSUE TITLE
Implement an additional stage in the Release pipeline to generate or update 'latest.version' files in blob storages.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#2394]
Ref issue: https://github.com/dotnet/release/issues/476
Ref issue 2: https://github.com/dotnet/release/issues/374

**This is a high-risk change.** Before implementing this change, we need detailed risk assessment in order to not affect our customers. As part of the design, please find answers to the following questions.

* What automation depends on the `latest.version`?
  dotnet-install-scripts depend on it to install the latest version of .NET for a given channel. [Investigation of how the scripts resolve versions](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1103/Investigation-of-.NET-install-scripts-incidents)
* What is the risk associated with this change? Specifically, what can be the implications of incorrectly updating the files?
   It can cause install scripts to install a wrong version which would have a huge impact on all CI pipelines that use .NET
* How are we going to test the change prior to enabling it in production?
  We should set up a test environment that is as close to the production one as possible but doesn't affect it (ideally setting up a separate subscription for testing)
* How do we verify the implementation is correct and the correct `latest.version` files were created?
* In case we affect external customers, how do we communicate the problem?
* What is the rollback scenario?

Add a new stage after the existed "Update Install Scripts Aka.ms links" stage and before the "Release Completion Notifications" stage.

... --> Update Install Scripts Aka.ms links --> ##new stage## -->Release Completion Notifications

The new stage must take SDK, Runtime, ASP.Net Runtime etc. versions from the `config.json` file and create corresponding files in the `dotnetcli` storage account. The list of folders is described in the ref issue.

/cc @rbhanda 

## Tasks
- https://github.com/dotnet/release/issues/686
- https://github.com/dotnet/release/issues/687

**Comment by MilenaHristova** [comment]
The change is tracked https://github.com/dotnet/release/issues/374 . Closing this as duplicate
