### ISSUE TITLE
Evaluate and document tools and scripts used in the Staging and Release pipelines

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#2397]
## Motivation:
We want to ensure that the release infrastructure is testable so that changes can be implemented with high confidence. In order to achieve this, we must do an audit of all tooling and scripts used in the pipelines, clarify the ownership, make sure the usage is well documented and tools have good test coverage.

## Goals:
We want to make sure that our infrastructure is well tested.

## Work items:
* Evaluate the `dotnet-release` repository and prepare a catalog/document of all internal/external tools and scripts, who own them. If we use external tools, check how far we are from latest version. You can prepare a table with columns: tool/script, owner, how far from latest, covered with tests, etc.
* Assess whether there are any scripts that could be rewritten in C# and then covered with tests.

**Comment by tkapin** [comment]
@andriipatsula - Why is this blocked? What needs to happen to unblock this?

**Comment by andriipatsula** [comment]
Initial evaluation is done. We have a wiki which describes tools and scripts used in the Release and Staging pipelines. As part of this effort, we need to review the document and create issues for scripts we'd like to rewrite in C# and code we 'd like to cover with Tests. Moving to "On Radar" column.

**Comment by MilenaHristova** [comment]
@andriipatsula shouldn't we close this? We finished the evaluation with [Tools wiki](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1048/Tools-and-scripts-used-in-the-.NET-Staging-and-Release-pipelines) and [Document the release pipeline issue](https://github.com/dotnet/arcade-services/issues/2959). I think opening issues for the problematic scripts will be an ongoing process that's separate from this.

**Comment by andriipatsula** [comment]
As discussed with @MilenaHristova , creating an epic placeholder https://github.com/dotnet/arcade-services/issues/3027 and closing this.
I have introduced a new milestone: https://github.com/dotnet/arcade-services/milestone/36
