### ISSUE TITLE
Staging pipeline to publish to approved channels

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade-services#2400]
In Staging pipeline, manifest.json contains the information about all the builds that are involved in the gather drop and the channel its publishes to. 

A user configured a wrong channel - General Testing to one of the builds, cos of that the build was trying to publish to General testing and the build failed. 

Solution: Scan the channels used in the manifest.json when creating the release config, and verify that they are all "approved"? 

Eg Error : https://dev.azure.com/dnceng/internal/_build/results?buildId=2120880&view=logs&j=06e47235-ea4e-5696-bf7a-60141ec0f646&t=23030f86-a850-5629-e37b-e34af5164200

Error : Publishing didn't expect that a random channel (here General Testing) would be used for release

**Comment by pavel-purma** [comment]
We will re-design whole publishing not to use v3 publishing
