### ISSUE TITLE
Remove publishing to public containers in Staging pipeline 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade-services#2407]
We noticed that we create public containers in Staging pipeline and publish to them but the assets are not used in the release pipeline. The staging pipeline creates public containers for public builds but really all builds are internal? 

A list of the containers that the staging pipeline is publishing to: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1013/Storage-accounts-containers-feeds-used-in-the-Stage-DotNet-and-the-Stage-DotNet-Test-pipelines
https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1011/Blob-storages-and-feeds-that-the-release-pipeline-depends-on

Linked issues:
- https://github.com/dotnet/arcade-services/issues/2404

**Comment by pavel-purma** [comment]
There are actually also releases which are public
