### ISSUE TITLE
 Ensure that the v-team responsible for the Release infrastructure has access to the key vaults utilized by the staging and release pipelines.

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#2410]
In the https://github.com/dotnet/arcade-services/issues/2630 issue, the release infrastructure team discovered that the Secret Manager tool for the secret autorotation does not have access to:
* dotnetstagetokens
* dotnetstagekeys
* dotnetclitokens

Since Ilya and Matt M. were OOF and nobody else has access to those key vaults, the Staging pipeline was blocked. We must ensure that @andriipatsula , @MilenaHristova , @epananth , @dkurepa have access.

We also need access to the storage accounts that the staging pipeline publishes to:
- dotnetstage
- dotnetchecksumsstage

**Comment by MilenaHristova** [comment]
apart from key vaults we can consider accessing storage accounts, here is a list of all storage accounts and feeds that the pipelines publish to https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1011/Blob-storages-and-feeds-that-the-release-pipeline-depends-on
Also linking this issue that's connected https://github.com/dotnet/arcade-services/issues/2419

**Comment by riarenas** [comment]
It's worth noting that Engineering services does not have access to most of the release infrastructure.

**Comment by MilenaHristova** [comment]
@rbhanda gave us access to `dotnetstagetokens`, `dotnetstagekeys`, `dotnetstage` and `dotnetchecksumsstage` 
@andriipatsula we should thing about organizing it so only groups have access and not individual people

**Comment by MilenaHristova** [comment]
> > gave us access to dotnetstagetokens, dotnetstagekeys, dotnetstage and dotnetchecksumsstage
> 
> Just so I'm clear, who is "us"? The ProdCon team?

Currently it's the release infrastructure v-team(@andriipatsula , @epananth and me) and @tkapin

**Comment by andriipatsula** [comment]
@Ilya provided us an access to `dotnetstagekeys` (view secrets permissions). I double checked that we have access to other. Closing it.
