### ISSUE TITLE
.NET release pipeline failing on Github repo tagging

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2415]
The release pipeline has been failing with the same error for .NET 8 since we started releasing it. We should fix this
https://dev.azure.com/dnceng/internal/_build/results?buildId=2178726&view=logs&j=cb266801-13d1-545b-bc71-d737c4aa47e6&t=698bf5eb-9a2c-5d2d-4822-66e45009e83b

**Comment by MilenaHristova** [comment]
@dkurepa this is done right?

**Comment by andriipatsula** [comment]
Resolved
