### ISSUE TITLE
`Publish Post-Signing Assets` fails to publish to `dotnet-8` feed

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#2417]
Publishing to `dotnet 8` feeds fail in the `Publish Post-Signing Assets` stage because there are some major-version changes that were not done. For this publishing stage dynamic feeds are generated in `create-feeds.proj` and serialized to `dynamic-feeds.json` file. There need to be some changes made in the template for the `json` file in order to have all the expected properties for the new major version

**Build** https://dev.azure.com/dnceng/internal/_build/results?buildId=2130286&view=logs&j=06e47235-ea4e-5696-bf7a-60141ec0f646&t=23030f86-a850-5629-e37b-e34af5164200

**Failure** `The property 'dotnet8' cannot be found on this object. Verify that the property exists`

**Goal**
Document all changes that need to be made when releasing a new major version of .NET

**Comment by MilenaHristova** [comment]
Issue for documenting major version release changes: https://github.com/dotnet/arcade-services/issues/2401

**Comment by andriipatsula** [comment]
> Issue for documenting major version release changes: #2401

@MilenaHristova , is there anything left for us to do in scope of this issue?

**Comment by MilenaHristova** [comment]
> @MilenaHristova , is there anything left for us to do in scope of this issue?

we should make sure all steps are listed
