### ISSUE TITLE
Produce patch-agnostic aka.ms links for latest sdk bands for each major/minor version

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade-services#2444]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See discussion here: https://github.com/dotnet/installer/issues/11040

**Comment by andriipatsula** [comment]
Closing this as the issue is over 2 years old and we don’t have plans to work on this in the near future. As it was mentioned above:
> the link structure is `aka.ms/dotnet/<version>/dotnet-sdk-<platform>-<arch>.<extension>`
