### ISSUE TITLE
Make the Stage-DotNet pipeline's continueOnErrors more granular

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade-services#2445]
Currently we're continuing on error for every step in every stage with an override. We could be more granular by using vso logging to fail / continue on error in very specific cases.

cc/ @adiaaida

**Comment by andriipatsula** [comment]
Closing this as the issue is almost 2.5 years old and we don’t have plans to work on this in the near future. In case you believe the issue needs resolution - please reopen it and provide a reason.
