### ISSUE TITLE
Explore pushing to nuget.org staging location during stage-dotnet

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#2448]
To get more 'complete' verification of nuget packages, consider pushing to the nuget.org staging location. Questions that need to be answered first:
- Security implications? - Is it visible to the public?
- What errors will it catch above and beyond our current verification.

**Comment by andriipatsula** [comment]
@mmitche , Is this issue still relevant, in your opinion?

**Comment by mmitche** [comment]
I believe NuGet staging is still public. So this is not an option for us since basically all servicing/GA releases are internal
