### ISSUE TITLE
Perf improvements for staging pipeline

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#2449]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The staging pipeline has some slowness. While it doesn't matter a lot of the time (a lot of the time, the staging is done overnight), when it does matter how fast it goes (like last night with the nuget client fix), it can be problematic for it to take a long time to get to the staging drop.

The primary driver behind the slowness appears to be the size of the overall artifacts. For instance, between the raw shipping and non-shipping artifacts uploaded from gather-drop, there are 17GB of artifacts. We should also assume that .NET's outputs will only increase in size over time as the number of platforms and architectures increases.

We upload and download these multiple times during the pipeline, and not all in parallel jobs For example, `Validate Signing Inputs` will download the whole drop before anything else in the stage can proceed. The other stages also download the drop. Same with `Validate Signing Output`. While this design makes sense, and is clean, it's destined to be very slow when there are large artifact stores.

To reduce the length of the pipeline (< 2 hrs to get to staging, without post build signing), it may be easiest to reduce some of the copying. Some ideas:
- **In all of the validation stages, do we need the full drop?** - Can we reduce the size by only selecting what we need as inputs?
- **Use logging commands to do async upload** - I think there are a bunch of places where we are doing processing of artifacts where we can do async upload. Some examples:
  - In gather-drop, rather than downloading the whole drop form the internet, then uploading, we should have gather-drop emit logging commands for the upload as files are created.
  - In the signing stage, do the same, as "final" artifacts are produced. Probably in signtool?

**Comment by andriipatsula** [comment]
@mmitche , Is this issue still relevant, in your opinion? Is it something we need to implement for the new "X hours SLA" initiative?

**Comment by mmitche** [comment]
We did implement quite a lot of this (especially the validation job removal) in emergency mode. The second bit about async upload is probably less useful overall, given that Pipeline artifact uploads are generally much faster anyway. I think closing this is fine.
