### ISSUE TITLE
Remove [SetUp] Tag from Test Data Initialization in PackageHelpersTest

### ISSUE THREAD

**Issue by Tohron** [dotnet/arcade-services#2450]
Chad raised concerns about the use of the [SetUp] tag in
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/12458?_a=files&discussionId=59293&path=%2Fsrc%2FMicrosoft.DotNet.Release%2FMicrosoft.DotNet.ReleaseLib.Tests%2FPackageHelpersTests.cs

This issue is for replacing that usage with a better implementation.

**Comment by andriipatsula** [comment]
Closing this as the issue is almost 3 years old and we don’t have plans to work on this in the near future. In case you believe the issue needs resolution - please reopen it and provide a reason.
