### ISSUE TITLE
Ensure gather-drop fails when the same package version with different contents is present in the drop

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#2452]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Ensure that if you have a package that has the same version another package, but different contents, gather-drop fails. Basically if we have two of the same version of Microsoft.NETCore.App referenced in a drop, they should be the same package.

**Comment by andriipatsula** [comment]
@mmitche , do you think this is still relevant? Is this something we want to improve in the near future?

**Comment by mmitche** [comment]
I don't think so. We have coherency checks for this now.
