### ISSUE TITLE
SDL runs should tag issues with the branch/commit that the issue corresponds with

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade-services#2453]
Using the -Path-Source parameter to the guardian script, we can add an additional tag to issues that guardian opens that give information like the corresponding repo/branch or the commit sha, to make discoverability easier.

**Comment by andriipatsula** [comment]
It seems, this issue is related to Arcade and not related to the .NET Release Infrastructure. Moving it out of https://github.com/dotnet/arcade-services/milestone/25

**Comment by michellemcdaniel** [comment]
Just a clarification, this issue was created for the SDL runs done out of the Stage/Validate-DotNet pipelines. It is *not* related to Arcade. Validate-DotNet uses the Stage-DotNet infrastructure to run nightly on those repos that have onboarded, so that partner teams could remove SDL and various other validation legs from their official builds. The SDL results that come out of those builds often have tags related to dotnet-release rather than the repo/branch/commit combo from the actual repo that we enlisted in (ie, runtime, aspnet, sdk, etc), and it was often confusing for the product teams to identify which branch had the SDL issue (they would look at main, rather than a release branch, for example, and not be able to repro). This is 100% a release process issue.

**Comment by andriipatsula** [comment]
Thank you for the clarification! I don't believe we will work on this in the near future. I am considering closing this till the next request as the issue is ~4 years old.

**Comment by missymessa** [comment]
SDL is provided via 1ES PT now. Closing.
