### ISSUE TITLE
The auto-generated tags have the wrong message

### ISSUE THREAD

**Issue by Anipik** [dotnet/arcade-services#2457]
Historically we have been using tags with  messages like ".Net Core 3.1.5"
The auto-generated tags uses the last commit message as a tag. 

eg for core-setup 3.1.5 the tag message is 
```
Merged PR 8041: [internal/release/3.1] Update dependencies from dncen…
…g/internal/dotnet-corefx

This pull request updates the following dependencies

[marker]: <> (Begin:d857f0c2-af97-43df-e8df-08d76e1cf1e0)
## From https://dev.azure.com/dnceng/internal/_git/dotnet-corefx
- **Subscription**: d857f0c2-af97-43df-e8df-08d76e1cf1e0
- **Build**: 20200520.1
- **Date Produced**: 5/20/2020 5:36 PM
- **Commit**: 620cea9ccf0359993e803c900059932966399584
- **Branch**: refs/heads/internal/release/3.1
- **Updates**:
  - **Microsoft.Private.CoreFx.NETCoreApp**: from 4.7.0-servicing.20269.2 to 4.7.0-servicing.20270.1

[marker]: <> (End:d857f0c2-af97-43df-e8df-08d76e1cf1e0)
```

The timestamp on the tags is also 27 days ago, not sure if we should have these tags before the actual release
cc @mmitche @wtgodbe @ericstj

**Comment by andriipatsula** [comment]
Closing this as the issue is almost 4 years old and we don’t have plans to work on this in the near future. In case you believe the issue needs resolution - please reopen it and provide a reason.
