### ISSUE TITLE
Prep ring should validate that drop is coherent

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade-services#2464]
-  Is this issue blocking (yes/no): no
-  Is this issue causing unreasonable pain (yes/no): no

The old drop gathering tool fails when multiple repos with the same version are specified. I think this behavior is good, because in stabilized builds, it's impossible to publish multiple packages with the same version number to the NuGet gallery. This should be caught as early as possible so it can be rectified.

The new gather-drop functionality should also catch this.

(I don't have full context on what happened in a particular instance where this *seems* to not have been caught, but filing the issue to track to make sure it isn't lost.)

**Comment by andriipatsula** [comment]
Closing this as the issue is almost 4 years old and we don’t have plans to work on this in the near future. In case you believe the issue needs resolution - please reopen it and provide a reason.

**Comment by mmitche** [comment]
This actually got done. Prep does validate coherency. So closed as completed.
