### ISSUE TITLE
How do I extend retention period of existing symbol indices (without symbol packages)?

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade-services#2466]
At release time, expiration date needs to be [extended from 180 days to 10950 days (30 years)](https://github.com/dotnet/core-eng/issues/3382). In earlier infra, this was done by publishing the same symbol packages again with the longer expiration date.

How is this done when some bits aren't in the symbol packages?

I imagine you *could* by downloading all the bits and pushing them back up, but how is that done in a release context? Is there tooling?

**Comment by andriipatsula** [comment]
Closing this as the issue is almost 4 years old and we don’t have plans to work on this in the near future. In case you believe the issue needs resolution - please reopen it and provide a reason.
