### ISSUE TITLE
Automate validating sourcelink information - for Windows PDBs

### ISSUE THREAD

**Issue by shawnro** [dotnet/arcade-services#2467]
In the past we have accidentally included links to dnceng instead of github.  As of now, someone has to do a manual check to ensure all of these are correct.  This check should be something that we can automate and track continually

cc: @mmitche, @markwilkie , @danmosemsft, @Pilchie

**Comment by andriipatsula** [comment]
Closing this as the issue is almost 4 years old and we don’t have plans to work on this in the near future. In case you believe the issue needs resolution - please reopen it and provide a reason.
