### ISSUE TITLE
ToolsError build failures in 'official/dotnet/arcade-services/refs/heads/master' - '20190315.5'

### ISSUE THREAD

**Issue by robertborr** [dotnet/arcade-services#247]
@dotnet-mc-bot commented on [Sat Mar 16 2019](https://github.com/dotnet/core-eng/issues/5519)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=125824
  - **Agent:** 
  - **Error log:** ContinueOnError: False...

@robertborr

---

@robertborr commented on [Mon Mar 18 2019](https://github.com/dotnet/core-eng/issues/5519#issuecomment-474059008)

The build timed out - you may wish to allocate more time.

F:\workspace\_work\1\s\.dotnet\sdk\2.1.504\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(129,5): error MSB4220: Waiting for the currently executing task "GenerateDepsFile" to cancel. [F:\workspace\_work\1\s\src\Maestro\SubscriptionActorService\SubscriptionActorService.csproj]
F:\workspace\_work\1\s\.dotnet\sdk\2.1.504\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(129,5): error MSB4220: Waiting for the currently executing task "GenerateDepsFile" to cancel. [F:\workspace\_work\1\s\src\Maestro\SubscriptionActorService\SubscriptionActorService.csproj]
##[error]The operation was canceled.

**Comment by MattGal** [comment]
@robertborr please reclassify Timeouts as Timeout in the future.
