### ISSUE TITLE
Rename files & folders in dotnet/release to make more sense

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2470]
Migrated from https://github.com/dotnet/core-eng/issues/13255

@jonfortescue wrote:

i.e. make the nomenclature match Azure DevOps. Rings -> phases, steps -> jobs or steps where appropriate, etc.

**Comment by premun** [comment]
The dotnet/release repo is not used much for anything, we can refactor there if we feel like it but closing this
