### ISSUE TITLE
Break up the "IRemote" class in arcade-services

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2497]
Migrated from https://github.com/dotnet/core-eng/issues/10084

@ChadNedzlek wrote:

It's a god class that does far too much, making it hard to write tests (because you have to mock out dozens of methods... or know way too much about the implementation to know what methods it's actually calling).

Some of our web services actually call _our own web services_ because the remote is hiding a recursive web call in here.

it needs to get broken up.

**Comment by premun** [comment]
Ok, I believe this has now been resolved.

There are still few more cases where we pass dependencies as parameters but I think that's a different problem. Both `Remote` and all of the `MaestroBarClient` partial implementations (that throw `NotImplementedException`) have been fixed
