### ISSUE TITLE
[darc/maestro++] Add `update` parameter to Darc

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade-services#2529]
Add an `update` (or similar) parameter to Darc so that user can use it to update Darc itself. Something like:

```
$> darc update
$> Updating Darc to version x.y.z ... done.
$> 
```

/cc @mmitche @riarenas @epananth

**Comment by premun** [comment]
I unfortunately don't think this is possible the way the .NET tools are designed so `darc-init.ps1` will have to do
