### ISSUE TITLE
[darc/maestro++] Use JSON as the output format

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade-services#2564]
Currently Darc outputs the results of some commands in YAML. There has been several request, including build from source, to change the output to JSON.

FYI: @mmitche @chcosta @crummel 

Rough stab at what could easily-ish be supported by json:

- [x] add-channel
- [ ] add-subscription
- [ ] add-build-to-channel
- [ ] delete-build-from-channel
- [x] gather-drop
- [ ] get-asset
- [ ] get-build
- [x] get-channels
- [ ] get-default-channels
- [ ] get-dependencies
- [ ] get-dependency-graph
- [ ] get-health
- [ ] get-latest-build
- [ ] get-repository-policies
- [ ] get-subscriptions
- [ ] set-repository-policies
- [ ] update-build
- [ ] update-subscription
- [ ] get-goal

**Comment by premun** [comment]
darc already supports JSON in many commands, we can add support to others if there's need but closing this
