### ISSUE TITLE
[darc/maestro++] Public/anonymous BAR access

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade-services#2566]
Is this planned? For example, anonymously seeing the latest core-setup build with this URL:

https://maestro-prod.westus2.cloudapp.azure.com/api/builds/latest?repository=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcore-setup&api-version=2018-07-16

Right now, I get a 401 anonymously, and the results I want if I provide my auth.

In particular, Tizen builds used to be triggered by changes on dotnet/versions. How can we accomplish the same with BAR with dotnet/versions publishing turned off?

@markwilkie @mmitche

**Comment by premun** [comment]
External contributors can no longer use Maestro or darc anymore
