### ISSUE TITLE
[darc/maestro++] darc doesn't use Arcade CLI

### ISSUE THREAD

**Issue by chcosta** [dotnet/arcade-services#2576]
It looks, cursorily, like darc makes use of whatever dotnet is on the machine.

```
D:\demo\hello-demo>darc
A fatal error occurred, the required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\chcosta\.dotnet\tools\.store\microsoft.dotnet.darc\1.0.0-beta.18517.1\microsoft.dotnet.darc\1.0.0-beta.18517.1\tools\netcoreapp2.1\any\].
If this is a framework-dependent application, install the runtime in the default location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

Arcade is supposed to be fully bootstrappable, and installs a local copy of the cli under the `.\.dotnet\` folder.  Yes, Arcade will actually use the machine wide install of the CLI if available, but I think there's lots of scenarios where a dev might not have / want one of those.  This is useful...

```
If this is a framework-dependent application, install the runtime in the default location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

… but it would be nice if, on a clean machine (with no cli installed machine-wide), if you just restored darc and it started working.

FYI @mmitche @jcagme

**Comment by premun** [comment]
`darc` is a .NET tool and gets a binary created when it is installed
