### ISSUE TITLE
[darc/maestro++] Darc should be buildable from source

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade-services#2578]
I noticed issues about using Octokit https://github.com/dotnet/arcade-services/issues/2580 and VSTS C# libs https://github.com/dotnet/arcade-services/issues/2579 in Darc. This sounds like a great idea, but I want to make sure it's implemented in a way that leaves Darc able to build from source.

If Octokit and VSTS APIs can build from source, ok, but it would be preferable not to build them at all. The builds take time, and the capabilities won't be used in source-build.

/cc @alexperovich @jcagme 

---

I haven't looked into every one, but these are unknowns when it comes to source-build:

* Microsoft.AspNet.WebApi.Client
* Microsoft.Azure.KeyVault
* Microsoft.Azure.Services.AppAuthentication
* [Microsoft.IdentityModel.Clients.ActiveDirectory](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/tree/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory)
* Microsoft.Rest.ClientRuntime
* Microsoft.Rest.ClientRuntime.Azure
* Microsoft.TeamFoundation.DistributedTask.Common.Contracts
* Microsoft.TeamFoundationServer.Client
* Microsoft.VisualStudio.Services.Client
* Microsoft.VisualStudio.Setup.Configuration.Interop
* [Newtonsoft.Json.Bson](https://github.com/JamesNK/Newtonsoft.Json.Bson)
* [Octokit](https://github.com/octokit/octokit.net)
* [YamlDotNet.Signed](https://github.com/aaubry/YamlDotNet)

An easy way I see to do this is to split code that needs to use these dependencies into separate csproj's, condition the dependency, and condition some small part of the code to link in (or not) web client capability. (`Microsoft.DotNet.Maestro.Client` is an example of something that's already split off!) The property `ExcludeFromSourceBuild` is used to skip a project during source-build.

I can imagine something fancier being done, where there's a real extensibility point on Darc. The user could choose to download some extra packages (or something) to enable web client capabilities.

**Comment by premun** [comment]
We have made a decision last year that building darc from source is not a requirement
