### ISSUE TITLE
Darc needs better unit test infrastructure

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2585]
Migrated from https://github.com/dotnet/core-eng/issues/10281

@missymessa wrote:

Darc functionality is mainly tested using scenario tests, and we could do a lot better with unit testing functionality.

We will likely need to introduce some sort of dependency injection into the darc cli and darclib to be able to sanely add tests.

**Comment by premun** [comment]
This is already covered in the arcade service debt epic, closing
