### ISSUE TITLE
Rework how Maestro++ calculates dependency update PR descriptions

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2586]
Migrated from https://github.com/dotnet/core-eng/issues/10249

@epananth wrote:

The way we are creating the PR description for the dependency update PRs (arcade-services)  has to revisited, we currently write some invisible markdown metadata into the pr description that we rely on for both:

* appending new updates to the original PR
* calculating the final commit message once the PR is merged.

We should be able to keep the state of dependency updates inside the PullRequest actor itself, so that it always has consistent information for all updates that have been applied, and can calculate both the PR description and the final commit message no matter what the current description is.

THis would also allow us to convey all the necessary information even if we have to truncate the PR description due to Azure DevOps' 4000 character limit by adding additional comments to the PR with any version updates that don't fit.

cc: @ChadNedzlek

**Comment by premun** [comment]
This is actually done now
