### ISSUE TITLE
[Arcade-services] Change unnecessary public properties in Maestro++ services to private fields.

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2589]
Migrated from https://github.com/dotnet/core-eng/issues/9037

@riarenas wrote:

Most of our services have things like the logger, and Database context as get-only properties and there doesn't seem to be a good reason to do so: [Such as these](https://github.com/dotnet/arcade-services/blob/8f13b91ac1fe0d3c4a951a7378dfd0de4ba2bfba/src/Maestro/DependencyUpdater/DependencyUpdater.cs#L50-L52)

 We should be able to change these to private fields, which will prevent people calling things they shouldn't be calling.

**Comment by premun** [comment]
I believe this was fixed with quite a few refactors we did in this space, closing
