### ISSUE TITLE
Guidance / Policy for the use of feature flags

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2590]
Migrated from https://github.com/dotnet/core-eng/issues/8700

@riarenas wrote:

Now that we have started using feature flags in Arcade-Services, we should come up with some guidance on (not a comprehensive list):

* When is a feature flag appropriate?
* How do we avoid having feature flags scattered all over the code?
* Policy for cleanup of the feature flags

**Comment by premun** [comment]
We don't have feature flags anymore, I think this is not relevant much anymore since everything changed twice over
