### ISSUE TITLE
Be able look up builds in Maestro++ using the AzDO build number

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2592]
Migrated from https://github.com/dotnet/core-eng/issues/6701

@missymessa wrote:

Our customers want an intuitive way of looking up previous builds. Currently, we can do this using the BAR build ID, but that's not an intuitive way for our customers. We should be able to look up the build using the AzDO build number instead.

**Comment by premun** [comment]
Based on the discussion in the issue, I think this was handled in c54e38e5279d582ce71812733f9894c487de46d4
