### ISSUE TITLE
Dependencies missing from BAR

### ISSUE THREAD

**Issue by dotnet-bot** [dotnet/arcade-services#2594]
Migrated from https://github.com/dotnet/core-eng/issues/5350

@chcosta wrote:

Dependencies which are a part of source build, but do not publish using dependency flow end up causing incoherent builds.  Source build is not able to determine which version of the asset is needed because it is not reported to BAR and then someone must manually go to a repo (like core-sdk) and trace back to find which version of the dependency is needed so that it can be built.

Repos:

- [ ] [Application-Insights](https://github.com/dotnet/core-eng/issues/5360)
- [x] [NuGet-Client](https://github.com/dotnet/core-eng/issues/5279)
- [x] Standard (pretty sure this has been resolved)
- [x] [VSTest](https://github.com/dotnet/core-eng/issues/5356)
- [x] [XLiff-Tasks](https://github.com/dotnet/core-eng/issues/5357)

**Comment by premun** [comment]
Seems like this one is done
