### ISSUE TITLE
Use default xcopy-msbuild version

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2603]
After updating dotnet-release to the newest arcade, our SigningValidation started failing because the new arcade needs msbuild 17.6, and we had 17.4.1 pinned in global.json. We should remove it and use the default version coming from arcade

**Comment by dkurepa** [comment]
https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/31694

**Comment by andriipatsula** [comment]
resolved
