### ISSUE TITLE
"General Testing" missing from list of channels in BARViz

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade-services#2641]
Customer noticed that the "General Testing" channel is not showing up in BARViz. It exists when you look at `darc get-channels`, but it's not showing up in the UI. It also shows up if you directly navigate to the URL: https://maestro-prod.westus2.cloudapp.azure.com/529/graph

**Comment by tkapin** [comment]
@directhex How much of a problem is this for you?

**Comment by tkapin** [comment]
@directhex - ping

**Comment by directhex** [comment]
I mean, it's a pain in the ass not having everything in the place it's supposed to be, but it's not hard to work around by just checking AzDO build logs & inferring package versions from published packages in there

**Comment by dkurepa** [comment]
This appears to be by design https://github.com/dotnet/arcade-services/blob/4e016bce2b9fe35a13bd19577082f42a1a0e5314/src/Maestro/maestro-angular/src/app/services/channel.service.ts#L39. I'm guessing that the 'General Testing' channel is classified as a `test` channel, so we're filtering it out.

**Comment by dkurepa** [comment]
We could maybe add a checkbox that could allow people to see testing channels too

**Comment by premun** [comment]
This channel will be back with the new front-end: https://product-construction-prod.wittysky-0c79e3cc.westus2.azurecontainerapps.io/
