### ISSUE TITLE
Build monitor should create issues in arcade-services when its CI fails

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2645]
We need to add the internal arcade-services CI into the build monitor configuration.

Similar change to https://github.com/dotnet/dnceng/pull/110

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
No release notes

**Comment by MilenaHristova** [comment]
This is done with https://github.com/dotnet/dnceng/pull/205
