### ISSUE TITLE
Update dependencies from `dnceng-shared` to fix CG alerts

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#2648]
Component Governance alert: https://dev.azure.com/dnceng/internal/_workitems/edit/4977

### Release Note Description
Not release note worthy

**Comment by MilenaHristova** [comment]
Pr updating dependencies: https://github.com/dotnet/arcade-services/pull/2292

**Comment by MilenaHristova** [comment]
There is another CG alert https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services/alert/7359939?typeId=6567134

**Comment by MilenaHristova** [comment]
It's green https://dev.azure.com/dnceng/internal/_build/results?buildId=2199541&view=results

**Comment by premun** [comment]
Putting in `Rollout`
