### ISSUE TITLE
Rollout process optimizations - roll out build artifacts instead of commits

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2660]
Currently, when we're doing a rollout to production, we're taking a commit from main, building from it, and publishing it to production. We believe the rollout should be based on rolling out well-tested binaries rather than commits. This is equivalent to how we release the .NET product itself, as the input to the staging pipeline are BAR IDs rather than commit SHAs.

Benefits
* Shorter rollout process as the binaries could be prepared and tested before the rollout

To figure out yet
* The production hotfixing process

**Comment by premun** [comment]
Adding to this:
- The rollout process should be made lightweight with as few potential breaks happening as possible.
- We should not publish packages to darc from the production branch, we do that already in the main build.

**Comment by dkurepa** [comment]
This issue is no longer applicable since we're rolling out docker images.
