### ISSUE TITLE
Enable BinSkim for the product repos

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#2661]
SDL config example: https://github.com/dotnet/runtime/blob/main/eng/sdl-tsa-vars.config
Build pipeline example: https://github.com/dotnet/windowsdesktop/blob/main/azure-pipelines.yml#L100-L103

List of product repos that have nightly validation

- [x] https://github.com/dotnet/aspnetcore - https://github.com/dotnet/aspnetcore/pull/49324
- [x] https://github.com/dotnet/efcore - https://github.com/dotnet/efcore/pull/31221
- [x] https://github.com/dotnet/runtime - https://github.com/dotnet/runtime/pull/89728
- [x] https://github.com/dotnet/msbuild - https://github.com/dotnet/msbuild/pull/8976
- [x] https://github.com/dotnet/sdk - https://github.com/dotnet/sdk/pull/33901
- [x] https://github.com/dotnet/installer - no need to scan as it's covered by the scans on other repos
- [x] https://github.com/dotnet/winforms - https://github.com/dotnet/winforms/pull/9467
- [x] https://github.com/dotnet/wpf - https://github.com/dotnet/wpf/pull/8016
- [x] https://github.com/dotnet/windowsdesktop - https://github.com/dotnet/windowsdesktop/pull/3698
- [x] https://github.com/microsoft/reverse-proxy - https://github.com/microsoft/reverse-proxy/pull/2189

Product repos that run SDL validation in-line in their builds:

- [x] https://github.com/dotnet/fsharp - https://github.com/dotnet/fsharp/pull/15640
- [x] https://github.com/dotnet/roslyn - https://github.com/dotnet/roslyn/pull/69081
- [x] https://github.com/dotnet/templating - https://github.com/dotnet/templating/pull/6872
- [x] https://github.com/dotnet/razor - https://github.com/dotnet/razor/pull/8967
- [x] https://github.com/dotnet/diagnostics - https://github.com/dotnet/diagnostics/pull/4087
- [x] https://github.com/dotnet/xdt - https://github.com/dotnet/xdt/pull/519

Additional product repos (no SDL enabled for these repos). 

We are not enabling BinSkim for these repos (based on the discussion with mmitche).

- https://github.com/dotnet/test-templates
- https://github.com/microsoft/vstest
- https://github.com/dotnet/emsdk
- https://github.com/dotnet/symreader
- https://github.com/dotnet/llvm-project
- https://github.com/dotnet/cecil
- https://github.com/dotnet/format
- https://github.com/dotnet/roslyn-analyzers
- https://github.com/dotnet/sourcelink
- https://dev.azure.com/dnceng/internal/_git/dotnet-wpf-int
- https://github.com/dotnet/xliff-tasks

**Comment by andriipatsula** [comment]
Commit example: https://dev.azure.com/dnceng/internal/_git/dotnet-arcade/commit/b41fa2738e7bb1a87cb21101725703e03b8191ab?refName=refs%2Fheads%2Fadd-binskim

But use `-ArtifactToolsList @("binskim")` instead of `-SourceToolsList @("policheck","credscan","binskim")` see: https://github.com/dotnet/arcade/blob/main/eng/common/sdl/execute-all-sdl-tools.ps1#L14C1-L16

**Comment by MilenaHristova** [comment]
The validation pipeline runs for a list of repos that's specified in https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=/eng/pipeline/tools/repos-to-validate.txt

**Comment by andriipatsula** [comment]
linked PRs:
https://github.com/dotnet/windowsdesktop/pull/3698
https://github.com/dotnet/msbuild/pull/8976

**Comment by andriipatsula** [comment]
@MilenaHristova are we going to enable Binskim for arcade-services ? https://github.com/dotnet/arcade-services/blob/main/azure-pipelines.yml

**Comment by andriipatsula** [comment]
What about the dotnet/arcade https://github.com/dotnet/arcade/blob/main/azure-pipelines.yml ?

**Comment by MilenaHristova** [comment]
@andriipatsula good question. My understanding was that we need to run it on the assets that are shipped as part of .NET.

**Comment by MilenaHristova** [comment]
> You can search for all repos using this query: https://github.com/search?q=repo%3Adotnet%2Fdotnet+%22%5C%22policheck%5C%22%22&type=code

the repos that are not in this issue are
https://github.com/dotnet/diagnostics
https://github.com/dotnet/deployment-tools
https://github.com/dotnet/xdt

**Comment by MilenaHristova** [comment]
BinSkim is now enabled for the full list of repos

**Comment by NikolaMilosavljevic** [comment]
@MilenaHristova @andriipatsula we need to enable Binskim in [dotnet/deployment-tools](https://github.com/dotnet/deployment-tools) repo. I looked at changes in some of the repos and it seems that this should be as simple as adding a single line to [`eng/sdl-tsa-vars.config`](https://github.com/dotnet/deployment-tools/blob/main/eng/sdl-tsa-vars.config):

```
-ArtifactToolsList @("binskim")
```

Is this all that's necessary for Binskim in `deployment-tools` repo?

**Comment by andriipatsula** [comment]
Hello @NikolaMilosavljevic , in your particular case you need to modify [azure-pipelines.yml#L105-L106](https://github.com/dotnet/deployment-tools/blob/main/azure-pipelines.yml#L105-L106)
1. Enable SDL validation (you have policheck and credscan specified in the configuration, but they are not running)
2. Add two lines to your pipeline as it was done for the dotnet/roslyn repository [azure-pipelines-official.yml#L393-L394](https://github.com/dotnet/roslyn/blob/main/azure-pipelines-official.yml#L393-L394)
