### ISSUE TITLE
Source Build release pipeline testability

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2668]
This epic touches on the official source build release pipelines and how to improve working with it.

## Context

The current pipeline has the following problems:

- **High bar for manual testing**
 Devs must push their dev branches into the internal AzDO mirror and queue a build. Queueing the build is error prone and time consuming as the dev must provide many input parameters and choose a staging pipeline to use. Determining the original pipeline is difficult too. There is a risk associated with not specifying the dry-run option which could result in mistakenly publishing announcements through official channels or uploading non-public artifacts to a storage account. This all makes it expensive to test each change.

- **No automated testing → changes are not guaranteed to be validated**
 When in a PR, moving changes back and forth between the PR branch in GitHub and the AzDO branch is again error prone and does not guarantee that the checked in code works. It happened that the YAML in main would not even compile/start.

- **Complicated and numerous code paths**
 The pipeline has following orthogonal flows:
  - Dry run vs Real – test mode behaves different
  - .NET 6.0/7.0 vs .NET 8.0 – differences between tarball and VMR flows
  - First run vs Repeated run – idempotency issues connected to some of the pipeline effects as the pipeline is expected to be run multiple times during a single release
  - Extensive configurability – the pipeline accepts many parameters that affect the behaviour (e.g. using an announcement gist)

    The above dimensions multiply and create numerous different code paths which are hard to exercise and validate or even account for during development.

- **Difficult/impractical to validate some parts**
 Some effects of the pipeline cannot be or are very hard to get validated and require a tedious manual setup such as creation of release PR, submission of discussions – devs have to create their private repositories, set up a token etc.

- **Poor local developer workflow** – Some parts of the release logic are ingrained in YAML and cannot be executed locally – running the pipeline is the only way to execute those bits. There will always be some YAML glue, but this layer is needlessly large at the moment and includes parts that could be extracted.

## Goals

1. **High confidence** - The source-build team has high confidence that the release pipeline will behave as expected when performing release activities. Devs have high confidence when making changes to the release pipeline that their changes behave as expected and do not introduce regressions.
2. **Productivity** - The source-build team can release the product in a timely fashion. Devs can easily make changes to the release pipeline.

## Objectives

- [x] #2669
- [x] https://github.com/dotnet/source-build/issues/3501
- [x] #2670
- [x] #2671
- [x] #2672
- [x] #2673 (partially complete, C# logic app will be implemented as part of `Post 8.0 / Pre 9.0` effort)

**Comment by premun** [comment]
# Pipeline analysis

## Pipeline inputs

The pipeline has the following inputs:

- **Release information** – mostly numbers and strings such as names of the release, tags, …
- **Associated pipelines overrides** – possibility to override which official builds are associated with the release
- **Flow controls** – skipping stages, running in dry-run mode, …
- **Stage-DotNet pipeline run** (pipeline resources) – the staging pipeline run to base this release off

Further, it pulls additional information from the Stage-DotNet run (JSON files with release information) and artifacts from the official builds. The artifacts and build differ between 6.0/7.0 and 8.0 flows.

## Effects

Below we list all the outside effects the pipeline has when run:

**Pre-release stage**

- [6.0/7.0] Source tarball is uploaded to a storage account
- [6.0/7.0] PR in dotnet-security-partners with the new source is created

**Mirroring stage**

- [8.0] Internal mirror of dotnet-dotnet is tagged
- [6.0/7.0] Sources pushed from merged PR from previous step are pushed into dotnet-security-partners organization
- Shipping packages are pushed to the dotnet-security-partners feed

**Release stage**

- [8.0] GitHub release is created in dotnet-dotnet
- Existence of a release tag is validated
- Announcement discussion is created in dotnet/source-build
- Prebuilts and source built artifacts are uploaded to a storage account
- PR that bumps versions is created in dotnet/installer

**Comment by premun** [comment]
## Proposal

Following specific implementation features are proposed:

- **Release metadata file** –All inputs – both pipeline parameters and gathered information from other builds – are put into a JSON file which is published as a pipeline artifact.
  - This file then serves as input of further actions in the release.
  - It is easy to mock during PRs/dry runs where we don't have all inputs at hand.
  - It is possible to validate the file contents – we can validate the info gather part but also humans can view the file during the release to verify content when something is off.
- **Three sets of pipelines** – the pipelines differ only in how they receive inputs and what environment they target. Additionally, non-production pipelines could also clean up after.
  - PR build to validate changes before merging – it should run over both a 6.0/7.0 and a 8.0 flow.
  - Test pipeline (currently called dry-run) to run pipeline against a test environment – ideally should differ from official pipeline in the target environment only.
  - Official release pipeline only run for actual releases.
- **YAML should go logic-free**
  - All logic should be runnable locally. YAML only serves as a vehicle to process and flow inputs/data.
  - We should consider the PR run to validate that the inputs are relayed well (e.g. we don't use wrong YAML variable).
- **Credential verification**
  - The dry-run pipeline should have a stage for verifying credentials / connections to all production environment so that we can validate the release will happen without issues.

### 2nd run behavior

The pipeline needs to be re-runnable without additional side effects. The table below suggests what should be done during a re-run.

| **Outcome** | **2nd run outcome** |
| --- | --- |
| Source tarball upload to storage account | Compare that the uploaded artifact matches the one we want to upload and fail when they don't match |
| PR in dotnet-security-partners created | Detect that PR is up/merged already |
| Internal dotnet-dotnet is tagged | Detect the tag and verify it's on the right SHA |
| Sources pushed into dotnet-security-partners | Detect that sources were pushed already, verify they're the same |
| Shipping packages pushed to dotnet-security-partners | Detect that packages are in the feed already during the push |
| GitHub release created in dotnet-dotnet | Detect that release exists and points to the same commit |
| Release tag verification | Same as 1st run |
| Announcement discussion | Detect that discussion exists already |
| SB artifacts uploaded | Compare that the uploaded artifact matches the one we want to upload and fail when they don't match |
| Release PR created | Detect that the PR exists already |

### Test environment

From the above it's clear that we will need to create a test environment that we'd target from the PR and dry-run pipeline. The list of test environment components to be created is the following:

- Test storage account
  - For source tarball and release artifact uploads
- Test version of dotnet-security-partners repo
  - Used for mirror PRs
- Private fork of dotnet/installer
  - Used for test release PRs
  - Used for test announcement discussions

## Concrete implementation ideas

- We should consider having a testable **C# app with the logic** that would be built and re-used in the pipeline.
  - It would have commands such create-release-announcement.
  - It would accept the JSON with inputs (it would have a command for creating it too).
  - It would have a dry-run mode (possibly set through env var) which would validate the expected inputs instead of real-world effects.
  - It would be more testable which could cover some blind spots during PR builds.
  - We should consider the ROI as many things the pipeline does are very easy to do in bash (which is not testable much though).
- Each step **validates its effect** so that we know the right thing happened. It's possible to run validation only too.
- We should set **clear rules for** when pipeline creates **warning / errors**. E.g. is it understandable when a dry run has warnings? etc…
- **dotnet/source-build is onboarded onto secret manager** so that environment access is kept functional.
- Consider the merger of the main release pipeline when working on this so that the two solutions are compatible.
- Consider having the **release infrastructure internally** only to allow better PR build tests.

**Comment by oleksandr-didyk** [comment]
All linked tasks completed or moved, closing as `Done`

**Comment by tkapin** [comment]
@oleksandr-didyk Can you provide concise summary of what has been done as part of this epic and what is the value? Thanks

**Comment by oleksandr-didyk** [comment]
## Completed objectives

### No manual testing and automated checks for PRs

Developers have limited interactions with the pipeline. All changes now undergo Pull Request checks that execute all code flows for all released .NET versions, providing concrete status to the developer / reviewers on the effect the introduced changes will have on the pipeline.

Additionally, any developer can execute the said pipeline for their specific feature branch through AzDO UI with a few simple clicks and no input parameters.

### Simplified code paths

The pipeline lost some of the code branching, specifically that related to versions and obscure configurability. Moreover, dry run has been completely removed, paving way for a `test` run - a run with the exact same execution path as for a proper release with the only difference being the resources (Azure storage accounts, GitHub repositories, etc) that are used for the pipeline effects / outputs.

### Supporting infrastructure for validating pipeline effects / outputs

Every run of the pipeline, be it for PR validation, testing or a full release, will always output expected artifacts and create needed effects. The only difference would be the target infrastructure - for an official release the official resources would be used, while for other runs test resources are utilized. This makes sure that:
 - everything in the pipeline is always ran for a specific release version, no matter the type of run
 - whenever these outputs / effects need to be validated manually, they are always available for inspection

## Impact

Overall, the effort contributed to a considerable increase of confidence in the Source-Build release infrastructure, its stability and reliability. During development the changes made were catching issues with changes to the scripts, the logic itself and interactions with outside resources, highlighting even more the need for this work in relation to something as important as the .NET release process.

## Work to be completed outside this effort

Improvements to the local dev workflow as well as addressing some of the other issues (such as over-reliance on scripts to execute pipeline logic) will be tackled as part of the pre-9.0 effort. This would guarantee that all the benefits of this work would be used to their fullest in the new release cycle.
