### ISSUE TITLE
Add staging environment for the Source Build release pipeline

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2670]
## Overview

Ideally, we'd put a list of things that need a staging variant and a list of access tokens / connection strings so that we can create a copy.

### Azure resources
| Type | Release Name | Release Subscription | Staging Name| Staging Subscription | Description |
|---|---|---|---|---|---|
| Storage account | [`dotnetclimsrc`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/06962174-fd78-47a2-9cf5-96d1e3975117/resourceGroups/dotnetbuild/providers/Microsoft.Storage/storageAccounts/dotnetclimsrc/overview) | [CPTAzure](https://ms.portal.azure.com/#blade/HubsExtension/ResourceMenuBlade/id/%2Fsubscriptions%2F06962174-fd78-47a2-9cf5-96d1e3975117) | [`sbpipelinevalidationtest`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/sb-release-validation-test/providers/Microsoft.Storage/storageAccounts/sbpipelinevalidationtest/overview) | [dnceng-internaltooling](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/overview) | Stores source and prereqs tarballs |
| Storage account | [`dotnetcli`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/11c6037b-227b-4d63-bee1-18c7b68c3a40/resourceGroups/dotnetcli/providers/Microsoft.Storage/storageAccounts/dotnetcli/overview) | [DotNetCLIArtifacts](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/11c6037b-227b-4d63-bee1-18c7b68c3a40/overview) | [`sbpipelinevalidationtest`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/sb-release-validation-test/providers/Microsoft.Storage/storageAccounts/sbpipelinevalidationtest/overview) | [dnceng-internaltooling](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/overview) | Stores SDK and source-build artifacts |
| Key Vault | [`EngKeyVault`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1/resourceGroups/KeyVaults/providers/Microsoft.KeyVault/vaults/EngKeyVault/overview) | [Dotnet Engineering services](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1/overview) | [`sb-validation-secrets`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/sb-release-validation-test/providers/Microsoft.KeyVault/vaults/sb-validation-secrets/overview) |  [dnceng-internaltooling](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/overview) | Stores PATs for GitHub / AzDO repos |
| Key Vault | [`dnceng-pipeline-secrets`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1/resourceGroups/KeyVaults/providers/Microsoft.KeyVault/vaults/dnceng-pipeline-secrets/overview) | [Dotnet Engineering services](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/a4fc5514-21a9-4296-bfaf-5c7ee7fa35d1/overview) | [`sb-validation-secrets`](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/resourceGroups/sb-release-validation-test/providers/Microsoft.KeyVault/vaults/sb-validation-secrets/overview) | [dnceng-internaltooling](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/84a65c9a-787d-45da-b10a-3a1cefce8060/overview) | Stores storage account keys and GitHub PATs |

### Other resources
| Type | Release Name | Staging Name | Description |
|---|---|---|---|
| NuGet feed | [`dotnet-security-partners`](https://dev.azure.com/dotnet-security-partners/dotnet/_artifacts/feed/dotnet) | [`dotnet-sb-validation`](https://dev.azure.com/dnceng/internal/_artifacts/feed/dotnet-sb-validation) | Stores NuGet package from staging pipeline |
| GitHub repository | [`.NET installer`](https://github.com/dotnet/installer) | [`installer` in `maestro-auth-test`](https://github.com/maestro-auth-test/installer) |
| GitHub repository | [`.NET VMR`](https://github.com/dotnet/dotnet) | [`VMR` in `maestro-auth-test`](https://github.com/maestro-auth-test/dotnet) |
| GitHub repository | [`dotnet-security-partners`](https://dotnet-security-partners@dev.azure.com/dotnet-security-partners/dotnet/_git/dotnet) | [`source-build-validation`](https://dev.azure.com/dnceng/internal/_git/source-build-validation) | Repo for mirroring VMR / installer into |
| GitHub repository | [`.NET source-build`](https://github.com/dotnet/source-build) | [`source-build` in `maestro-auth-test`](https://github.com/maestro-auth-test/source-build) |

<details>
<summary>Simplified resource usage in context of release flow</summary>

![resources_in_release_context](https://github.com/dotnet/arcade-services/assets/106967057/28af6e1b-289e-4a10-a595-02454bdaa4d2)

</details>

**Comment by oleksandr-didyk** [comment]
Closing as work items under this task would be incorporated into https://github.com/dotnet/arcade-services/issues/2671

**Comment by mthalman** [comment]
I can't think of anything else.

**Comment by oleksandr-didyk** [comment]
@ilyas1974 Matt Mitchel mentioned that you would be able to help us find the best place for the Azure resources needed in this issue. 

Specifically, we would like to create a storage account, a NuGet feed and a Key Vault to be used in the non-production (staging) AzDO pipeline.

**Comment by oleksandr-didyk** [comment]
Waiting on agreement for resource ownership & access

**Comment by oleksandr-didyk** [comment]
Received response on resources, resolving ownership and access models

**Comment by oleksandr-didyk** [comment]
Resources have been created and are being used in the `dotnet-release` Source-Build pipeline.

Further allocating them to a proper subscription / access model is described and tracked by https://github.com/dotnet/arcade-services/issues/2774
