### ISSUE TITLE
Add PR validation of Source Build pipeline

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2671]
## Overview

Every PR against `dotnet-release` affecting the Source Build release pipeline needs to have a PR build that will validate the changes.

The validation in question must adhere to the following principles:
- The build should be very similar to the real one but target a staging environment.
- The build should run a 6.0/7.0 and a 8.0 code path.
- The build should clean up after it's completed.

### Work granularity

PR validation could be introduced gradually by splitting it into three parts that correspond to stages in the current release pipeline. Once a given stage is added to the PR pipeline and is ready for use, it should be introduced to the main repo and utilized for any future PRs.

This approach would:
  - allow us to reap the benefits of this work quicker by introducing partial PR validation
  - split the review process into manageable chunks
  - minimize time spent waiting for staging resources to be created / become available for use in PR validation

### Second pipeline

Given that there inevitably be differences between the PR validation and the release pipeline, we should minimize the extra YAML / shell script / C# code that would need to be added / maintained.

Ideally, the files containing the actual pipeline would be the only deviation between the two. Everything else besides this _YAML glue_ should be isolated and re-used.

This could result in us having to isolate currently used logic into scripts or even re-write it completely into C#. Whatever we choose ease of testability and maintenance should be our main concerns here.

## Progress

  - [x] PR pipeline created with proper triggers added to the `dotnet-release` repository (~ 1 week)
  - [x] Pre-release stage validation has been added (~ 3-4 weeks)
  	- https://github.com/dotnet/arcade-services/issues/2725
  - [x] Mirror stage validation has been added (~ 2-3 weeks; ETA 09/15, closed on 10/02)
    - https://github.com/dotnet/arcade-services/issues/2871
  - [x] Release stage validation has been added (~ 2 weeks; original ETA 09/29, prolonged to ~10/11)
    - https://github.com/dotnet/arcade-services/issues/2943
  - [x] Pipeline cleans up any mutations performed (announcements, PR, etc)
    - https://github.com/dotnet/arcade-services/issues/3000 
  - [x] Pipeline warns about outdated staging pipeline usage (~ 1 day)
	- will be done as part of https://github.com/dotnet/arcade-services/issues/2977

**Comment by oleksandr-didyk** [comment]
Closing as all sub-tasks are complete
