### ISSUE TITLE
Separate dry-run into a dedicated pipeline

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2672]
## Context

The current pipeline has a dry-run mode that is triggered from an input pipeline parameter.
The pipeline is then riddled with if/else around this parameter.

## Goal
We should have the code as simple as possible without this dry-run branching and only target a dedicated private environment with test pipelines. This means we wouldn't run a real pipeline and forget to set the parameter by mistake. We would have a cleaner separation and pipeline run history for the real pipeline.

We can achieve the above by separating the dry-run mode into a dedicated pipeline.

**Comment by oleksandr-didyk** [comment]
Dry-run option has been completely removed as part of https://github.com/dotnet/arcade-services/issues/2671

Instead, a switch was introduce to distinguish between running a release or a test run:
![image](https://github.com/dotnet/arcade-services/assets/106967057/3f2d7398-6734-4284-a6cb-a0c2e58794df)

The option of having the test run in a separate pipeline is currently being discussed

**Comment by oleksandr-didyk** [comment]
After discussion with a broader team a decision was made to separate `release` and `test` pipelines for a multiple reasons, including but not limited to:
  - clear distinction between production and non-production pipelines
  - need for pipeline categorization based on its purpose (prod / non-prod)
  - need for run retention which would differ for release runs (unlimited retention) and test runs (retention limited to a few weeks / months)
  - easier visual distinction for developers using the pipeline
  - cheap implementation & minimal maintenance compared to having only one pipeline

**Comment by oleksandr-didyk** [comment]
PR - https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/35042

**Comment by oleksandr-didyk** [comment]
PR merged, closing as `Done`
