### ISSUE TITLE
Darc `update-dependencies --id ...` is very slow

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2681]
I've been using the `darc update-dependencies --id <barID> and it's been very slow. In particular, running the command in the sdk repo takes 1-2h, same for the installer repo. We should take a look at it and see why it's so slow

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
Improved performance of the `darc update-dependencies` command

**Comment by tkapin** [comment]
This is also being reported from time to time (2 times I'm already aware of) by the customers. This needs to be addressed.

**Comment by oleksandr-didyk** [comment]
Rolled-out with https://github.com/dotnet/arcade-services/issues/2742
