### ISSUE TITLE
Remove legacy CPD algorithm

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade-services#2687]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now we have defaulted the coherency calculation to use the strict algorithm and then fall back to using the regular coherency algorithm. We should remove the legacy algorithm once we're confident that we don't need the fallback anymore.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Remove the fallback to the legacy coherency algorithm.

**Comment by premun** [comment]
Putting in `Rollout`

**Comment by andriipatsula** [comment]
We found an issue and reverted changes. Reopening this one till I resolve the bug

**Comment by tkapin** [comment]
What was the issue? Is it described somewhere?

**Comment by andriipatsula** [comment]
Released this week: https://github.com/dotnet/arcade-services/pull/2859
We did ensure that everything looks good.

**Comment by mmitche** [comment]
!!!!!!!! :D :D :D
