### ISSUE TITLE
Latest git version does not support >1GB patches

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2710]
### Problem

Last October git introduced a 1GB cap on patch size due to some problems with types they use during parsing: https://github.com/git/git/commit/f1c0e3946e

This manifests when we're initializing new repositories such as [llvm-project](https://github.com/dotnet/installer/pull/16757).

### Solution

There is no specific exit code / error message for this, though they promised to add one.
This means we need to check the size of the patch and if it's too large, break it into pieces - ideally by recursively going and creating a patch for each folder below.
This should be quite cheap to implement as we already have the notion of patch and its application path. We already have >1 patches per repo too.

**Comment by andriipatsula** [comment]
rollout with https://github.com/dotnet/arcade-services/issues/2773#rollout-build
