### ISSUE TITLE
Improve arcade-services rollout issue

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade-services#2743]
List of minor improvements that can be done to the rollout issue `GitHub` template utilized by the `arcade-services` repository

- mention of Maestro's PR for the rollout merge commit (example: https://github.com/dotnet/arcade-services/pull/2741). An instruction should be added to the end for merge-commit merging this PR after the successful rollout (i.e. nothing was rolled back)
- add section for issue clean-up in Product Construction board (https://github.com/orgs/dotnet/projects/276):
	- move any issues in the `Rollout` column that may have been left-over from last week into `Done`
	- move the Rollout issue itself into `Done` after the rollout has been complete 
	- move issues in `Rollout` to `Done` once the rollout is successful
- fixup Kusto link to [this](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA51Qy07DMBC89ytWuTSWwg+k6gFUCfWCqhZxQSha4m1j5Eew10B5/DubUETgiE+r8ezM7GhqLUaCx0zx2PQY0RFTTOU2WBsyr3Vtgz/AEtRiZonhkniVI7IJXsCyMbqGgVFBszcx8Y7xQDUkjmYELf7BFLzNQN61cWSNpy21Ieo0Yu/w3JGkucjG6rWG5RLE4NfXlQQE48uJ29RFncgpO4fRvJK4YmSJ6mRpN8yDsaqAvB5QfJmgp+U+hgdqGSaH7kN0yA0LK/Xoy2H77Eu7gqLraucKaehjMevlSB6FbuebSOe9qD2hhXIkqfmdqHFILUrv5aTNn8ZFcCygkGGT761JHeQk1cEKY1soVX3Lh8T/019Rb8NxMLhBazQygR4hR57FYfEJhAtQpRgCAAA=) one
- together with PR link a link to the internal rollout build should also be provided

**Comment by premun** [comment]
We should verify that the production->main PR has no file changes (except when rolling back or hotfixing)
