### ISSUE TITLE
SDL validation fails to upload results to Guardian result repository

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#2780]
The Guardian tool fails to upload logs from SDL checks in product repo builds

Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2229541&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=66df1a84-4ac1-5ba1-6998-e011cc992fec

Error:

```
Process:
    Convert:
      Converting any raw tool logs to Sarif format ...
      Found 1 logs for tool binskim.
      Saved file D:\a\_work\1\.gdn\rc\binskim/001/binskim.sarif
      Found 1 logs for tool credscan.
      Found 1 logs for tool policheck.
      Saved file D:\a\_work\1\.gdn\rc\policheck/001/policheck.sarif
      Completed converting raw tool logs to Sarif format.
    Import:
      Importing results to the Guardian result repository...
Command execution FAILED with exit code '128'.

Command-line     : C:\Program Files\Git\cmd\git.exe rev-parse --show-toplevel
Working directory: D:\a\_work

fatal: not a git repository (or any of the parent directories): .git


Command execution FAILED with exit code '128'.

Command-line     : C:\Program Files\Git\cmd\git.exe rev-parse --show-toplevel
Working directory: D:\a\_work

fatal: not a git repository (or any of the parent directories): .git
```

**Comment by MilenaHristova** [comment]
The error doesn't occur in the validation pipeline https://dev.azure.com/dnceng/internal/_build/results?buildId=2229460&view=logs&j=5670356f-8b38-5a32-2003-b78bdacf9625&t=5ff1c3ca-338a-5910-4894-2feea98128a7&l=1111

The difference between implementations in the CI pipelines and the validation pipeline is the working directory, 
for CI it's the default value `$SourceDirectory=$env:BUILD_SOURCESDIRECTORY` which is `D:\a\_work\1`
for the validation pipeline the argument is set to `D:\a\_work\1\s` which is a git repository

**Comment by MilenaHristova** [comment]
Other findings
- `guardian init` needs to be called with a git repository as a working repository 
- in the staging pipeline the `dotnet-release` repo is cloned to `D:\a\_work\1\s` and all the repos which are getting validated are cloned to `D:\a\_work\1\s\s` so when we initialize guardian in the parent directory of `D:\a\_work\1\s\s` that happens to also be a git repo so there is no error (I don't know if that's a happy coincidence or intentional)
- if we initialize guardian in the repo itself and then set the same repo folder as target for the scan , guardian will also scan the `.gdn` folder which contains some packages and creates extra unwanted reports

**Comment by tkapin** [comment]
Was this reported to the Guardian team or is this something that should be fixed on our side?

**Comment by andriipatsula** [comment]
It is on our side. The bug has been existing for ~4y already. The goal of this issue was to figure out what are the side effects. @MilenaHristova, I suggest closing this one as investigated and reporting a separate issue-bug (or move the original one out of the "Automate BinSkim runs over official builds" milestone.)

**Comment by MilenaHristova** [comment]
it is on our side, in Guardians documentation it's mentioned in a few places that Guardian needs to be initialized in a repo 
"Can I run a security tool build task (e.g., CredScan) across multiple repositories?
A: No, Guardian analyzes the code in the repo in which it is running."

The action here would be to figure out a way to initialize Guardian inside the repo that's being scanned and avoid scanning the `.gdn` folder. I'll move it out of the milestone

**Comment by tkapin** [comment]
From my perspective, the primary thing to clarify is - do we have a legitimate reason to run guardian in another directory than inside the repo?
- If we have a good reason to do so, then we need to report our use-case to the guardian team and ask for a feature switch or update so we can run it this way without the error.
- If not, then we should change the way we run guardian, but I'd like to understand more why we did set guardian up this way first.
