### ISSUE TITLE
Maestro Application Gateway Rollout

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2781]
Currently, our arcade scripts are using a hardcoded Maestro endpoint that was generated on Cluster creation. This means that, in the event of migrating Maestro into a different cluster, we'd have to change the URL to the new one every time.
We want to replace this current approach with something more configurable: have a "front" URL that redirects to the actual Maestro endpoint, so that in the event of migration, we can just point the URL to the new endpoint.
We need to:
 - Figure out what we want to use for the redirection (some Azure resource, or maybe aka.ms)
 - Identify all places that need the change
 - Identify full list of repos that this change will need to flow to. It will have to be all repos, on all branches
 - Execute the plan

Important thing to note is that this change won't be disruptive.

**Comment by garath** [comment]
Using aka.ms makes me nervous. It has no SLA attached to it. 

Double check this, but... The Azure App Gateway we put in front of all our web services should be able to handle what you want here. It can accept traffic from a single permanent domain then route it to whatever backend you want (even at percentages, so you can slowly move traffic to the new service). So registering a custom domain, perhaps a subdomain to dot.net (like we do for helix) and point it to the app gateway.

**Comment by dkurepa** [comment]
Yup, I don't think using aka.ms would be a very good solution too.

> Double check this, but... The Azure App Gateway we put in front of all our web services should be able to handle what you want here. It can accept traffic from a single permanent domain then route it to whatever backend you want (even at percentages, so you can slowly move traffic to the new service). So registering a custom domain, perhaps a subdomain to dot.net (like we do for helix) and point it to the app gateway.

Thanks for the recommendation, I'll look into this!

**Comment by garath** [comment]
I had a look at the resource group and I think there is some trickiness (still totally doable though). I'll message you directly about it.

**Comment by dkurepa** [comment]
We are currently figuring which domain we should create the Maestro subdomain in

**Comment by dkurepa** [comment]
We have created the DNS A record pointing maestro.int-dot.net to IP address we're gonna use for Maestro

**Comment by dkurepa** [comment]
We have the DNS records now. We need to finish https://github.com/orgs/dotnet/projects/276?pane=issue&itemId=34379421 before we can do this

**Comment by dkurepa** [comment]
The staging environment has been fully configured.
The production environment Azure resources have been created, but things like GitHub authentication on BarViz  and GitHub hooks don't work yet. We will need to rollout https://github.com/dotnet/arcade-services/pull/3040 before we can start executing the [plan](https://github.com/dotnet/arcade-services/issues/3006)

**Comment by tkapin** [comment]
I believe the condition above is met now, any update on this?

**Comment by dkurepa** [comment]
The first phase of the plan has been executed. We are now making sure that the arcade updates are being flown to all of the repos/branches

**Comment by dkurepa** [comment]
The plan https://github.com/dotnet/arcade-services/issues/3006 has been executed. All of our automation is now using the Application Gateway. We still haven't deleted the Load Balancer, just in case we need it
