### ISSUE TITLE
Binskim hangs trying to resolve symbols from the symbol server

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#2787]
For some reason the Binskim tool hangs while running in an azdo pipeline with specified `--sympath SRV*http://msdl.microsoft.com/download/symbols` parameter.

- [x] Contact Binskim support
- [x] Contact Guardian support

If you specify `https` instead of `http`, the issues disappear. It seems that Azdo rejects http requests (a known limitation?), causing Binskim to hang while reaching the MS symbol server.

On the other hand, you can do `curl http://msdl.microsoft.com/download/symbols` and `curl` got a respond.

**Comment by andriipatsula** [comment]
PR https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/32883

**Comment by tkapin** [comment]
This was solved by using HTTPS instead of HTTP as the protocol.
