### ISSUE TITLE
Document the .NET CLI (dotnetcli) blob storage use

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade-services#2793]
Jose Aguilar asked us to help him resolve stability issues with the dotnetcli storage account. This account is used by the [dotnet-install scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). They observe issues with this blob storage mainly when the new major version of the product is released, i.e., around between February & April in both 2022 & 2023.

Examples of observed issues:
* Examples: Channel 7.0.2xx installed older SDK version and Channel 8.0.1xx installed wrong SDK version
* Common fix: Update to aka.ms link
* Reference: the last 3 incidents: [1771847](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1771847), [1774957](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1774957), [1774959](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1774959)

**The goal** of this is issue is to bring clarity into how the dotnetcli is set up and used by the release infrastructure. The result should be a (private) document (or a set of documents), that could be handed over to Jose's team.

* Document the format of the data (contract) stored on the dotnetcli
* Document how is this blob storage used by the infrastructure (i.e., what pipelines / steps change the data on the storage).
* Investigate if / how are the data changed manually during the release process
  * Implementing a well-defined procedure of any manual interactions with the data should be a follow-up issue
* Document the access rights to the storage
  *  Log issues for any follow-up work (such as investigating possibility to move the storage account to PME)

**Comment by tkapin** [comment]
I've started the [dotnetcli-storage](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1094/dotnetcli-storage) page on our wiki to document this special blob storage, please fill in the results of our investigations there.

**Comment by MilenaHristova** [comment]
This wiki page has a diagram of the publishing to various containers (including dotnetcli) https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1011/Blob-storages-and-feeds-that-the-release-pipeline-depends-on

**Comment by MilenaHristova** [comment]
waiting for some feedback on the doc from Jose

**Comment by MilenaHristova** [comment]
The dotnetcli usage is described in [dotnetcli -storage wiki page](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1094/dotnetcli-storage), we've discussed it with Jose Aguilar. This can be closed
