### ISSUE TITLE
[Darc] consider pointing to the patgeneratortool for instructions on how to set up the darc client

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade-services#2803]
Currently, the instructions that pop up in the UX after running `darc authenticate` mention the following:

> Create new Azure Dev Ops tokens at https://dev.azure.com/dnceng/_details/security/tokens (code read and build read & execute scopes are needed)

Previously, the PAT UI would allow you to create PATs for multiple organizations, so these instructions were sufficient, however, as security requirements have increased, this multiple-org PAT generation has been disabled through the UI, so a PAT created in this URI will not allow users to perform operations in other azure devops organizations such as devdiv.
 
We have a dotnet tool for generating PATs through the command line in https://github.com/dotnet/dnceng/tree/main/src/PatGenerator/Microsoft.DncEng.PatGeneratorTool that can easily support the darc PAT generation scenario:

`dotnet pat-generator --scopes build_execute code --organizations dnceng devdiv --expires-in 180`

We should consider updating the instructions for the authenticate command and for the darc setup documentation (https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md#step-3-set-additional-pats-for-azure-devops-and-github-operations) to have instructions on how to install and run the tool.

**Comment by dkurepa** [comment]
PR for the Darc instructions https://github.com/dotnet/arcade-services/pull/2843/files

**Comment by dkurepa** [comment]
PR for the arcade documentation https://github.com/dotnet/arcade/pull/13981

**Comment by dkurepa** [comment]
Both of the PRs have been merged. Arcade docs and `darc authenticate` instructions have both been updated with the instructions for the PatGeneratorTool
