### ISSUE TITLE
Retain production rollout builds

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2814]
We want to retain all of our production rollout builds, in case we want to go back and look at them for whatever reason.

Ideally, we would do this through automation, as a job in the pipeline

### Release Note Description
Retain arcade-services production builds

**Comment by dkurepa** [comment]
As a part of this issue, I retained all available production builds we had in AzDo

**Comment by dkurepa** [comment]
The PR has been merged. We will now retain all of our production builds, even if they're not successful

**Comment by MilenaHristova** [comment]
Rolled out with https://github.com/dotnet/arcade-services/issues/2850
