### ISSUE TITLE
Remove Application Insights from Darc

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2819]
Currently, Darc has application insight logging set up. The issue is that the Application Insights instance it's referencing doesn't exist anymore. We are going to remove that code for now, while we figure out what we want to do with it.

**Comment by dkurepa** [comment]
We're removing app insights as a part of https://github.com/dotnet/arcade-services/pull/2809

**Comment by dkurepa** [comment]
Application Insights has been removed in the PR above. We will create a follow up issue to bring it back in the future, once we figure out where we want to store the logs in

**Comment by MilenaHristova** [comment]
Rolled out with https://github.com/dotnet/arcade-services/issues/2850
