### ISSUE TITLE
Disable CG in codeql (autoinjected) pipeline

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#2839]
We are running CG in our main CI pipeline, so we don't need to run it in other places.
For some reason, it is not working properly in the codeql pipeline, and is red all the time https://dev.azure.com/dnceng/internal/_build?definitionId=1084. Based on the talks I had with other people, we can safely remove this auto injected step

**Comment by dkurepa** [comment]
https://github.com/dotnet/arcade-services/pull/2840

**Comment by dkurepa** [comment]
the PR has been merged

**Comment by MilenaHristova** [comment]
Rolled out with https://github.com/dotnet/arcade-services/issues/2850
