### ISSUE TITLE
Installer PR builds do not checkout correct VMR base branch

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#2854]
When a PR is opened against `release/8.0.1xx`, VMR should get checked out on that branch as well. It gets checked out at `main` though.

The reason for this is that `variables['System.PullRequest.TargetBranch']` is not a compile time variable for some reason.

Probably the fix would be to perform a full clone, unshallow the repo and check out the correct branch.

**Comment by mthalman** [comment]
This also needs to account for the `internal/*` branches.

**Comment by premun** [comment]
This has been fixed via https://github.com/dotnet/installer/pull/17656
