### ISSUE TITLE
Add a stage that publishes workload manifest packages in the release pipeline

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#2879]
Add a new stage to the release pipeline to publish the contents of nupkgs-core-manifest.txt after core NuGet packages have been validated and a stage that validates the manifest packages

**Comment by MilenaHristova** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/33510

**Comment by andriipatsula** [comment]
I pushed a commit to https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/33510 which adds one more job ("Ensure Workload Manifest Exists") for both "Push Workload Manifest NuGet Packages" and "Validate Workload Manifest Nuget Packages" stages.

**Comment by MilenaHristova** [comment]
PR is merged and waiting for next release run to make sure everything works correctly

**Comment by MilenaHristova** [comment]
The stage failed in release. Issue for the fix: https://github.com/dotnet/arcade-services/issues/2946

**Comment by MilenaHristova** [comment]
The fix was tested with the test pipeline, but is waiting for a production release run to get fully validated

**Comment by MilenaHristova** [comment]
Pushing workload manifest packages worked in the latest release pipeline run https://dev.azure.com/dnceng/internal/_build/results?buildId=2299039&view=logs&j=14e68c57-f8e4-5751-74f3-bd47878d2bfe&t=3b4781fa-baac-55b4-4207-6f04de92a263
The task is completed
