### ISSUE TITLE
Update the Product Construction entries in the Product Catalog

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade-services#2887]
Per the [Product Catalog entry @ 1ES Docs](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/product-catalog/product-catalog-wiki), the Product Catalog (PC) "is a convenient way for service owners to keep track of the engineering artifacts that are related to their specific product". With the recent urgent request to classify the pipelines as production / non-production, we need to have a good understanding of what pipelines we are responsible for.

The entries in the [Product Catalog](https://product-catalog-web.prod.space.microsoft.com/) are not up-t-date as they show only the dotnet-helix-machines repo and it's related pipelines.

**Objectives** of this issue are:
- [ ] Identify repos, pipelines and other assets that should be listed under the ".NET Engineering Services ProdCon" entry on the PC
- [ ] Have the list consulted with the Engineering Services to ensure we have a shared understanding of the resources ownership
- [ ] Sync with the release team on where the release infrastructure assets (dotnet-release repo and pipelines) should belong
- [ ] Update the PC to reflect the agreed state

**Comment by garath** [comment]
Let me know if you'd like someone added as a  owner for the ProdCon service in Service Tree.

**Comment by dkurepa** [comment]
I created this AzDo issue for the internal discussion https://dev.azure.com/dnceng/internal/_workitems/edit/5365

**Comment by garath** [comment]
(I replied in the AzDO issue.)

**Comment by dkurepa** [comment]
We're still figuring things out for the dotnet-release repo

**Comment by dkurepa** [comment]
All ProdCon repos and pipelines are now cataloged in Service Tree
