### ISSUE TITLE
Update Maestro to .NET 8  (target 11/2023)

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#2935]
### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

Update Maestro from .NET 6 to the latest LTS on .NET 8, after release.

The Extended support for .NET 6 (LTS) ends on 12 November 2024.

### Release Note Description

Updated Maestro to .NET 8

**Comment by premun** [comment]
We need to until Service Fabric supports .NET 8.0. Then we need to update SF.
We're on ServiceFabric 8.2
The newest is 10.0 which does not have a direct upgrade from 8.2 (there is some interesting versioning scheme that 8.2. goes to 9.1. which doesn't seamlessly go to 10.0).

**Comment by premun** [comment]
`arcade-services` are now using 8.0 SDK + Arcade but SF still doesn't support it and, based on previous .NET versions, won't until next June or so.
There are no official news or roadmap though..

https://github.com/microsoft/service-fabric/issues/1472
https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-versions

**Comment by premun** [comment]
This won't be necessary
