### ISSUE TITLE
Rotate an aspnetmaven PGP key

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#2937]
Ref: https://github.com/dotnet/arcade-services/issues/2411
See: https://github.com/dotnet/arcade-services/issues/2357

It must be done before November 2023.

**Comment by MilenaHristova** [comment]
I checked the original issue and saw that the secret expires in November 2024 so we don't need to rotate it soon.

**Comment by andriipatsula** [comment]
Ok, nice. So, we can close this one. Please double check that we have November 2024 everywhere.
