### ISSUE TITLE
Document and create a diagram of the release pipeline

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#2959]
Create a diagram / description of the stages in the release pipeline and the locations they publish assets to

**Comment by MilenaHristova** [comment]
Wiki page with the graph: https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1130/Release-pipeline

**Comment by MilenaHristova** [comment]
I added some information for each stage. The document is complete in my opinion, @andriipatsula do you have any comments?

**Comment by andriipatsula** [comment]
The graphs look great! If possible, it might be helpful to generate PNG images and add them as links since the graphs are quite large and difficult to read.

**Comment by MilenaHristova** [comment]
Added. Mermaid doesn't render sequence diagrams very well but it made the biggest diagrams more visible
