### ISSUE TITLE
Always use HTTPS for Maestro Authentication redirection url parameter

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3004]
When we're logging into Maestro, we're using a GitHub app to authenticate ourselves. One of the parameters we're giving GitHub is the redirect_url, the url we want to be redirected to after authenticating.
Currently, when you authenticate on the new, maestro.int-dot.net url, it's trying to use http, because the `locator` variable sees that the cluster is talking to the application gateway via http (we're using https between us, the client and the gateway).
### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description
Always use HTTPS for Maestro Authentication redirection url parameter

**Comment by dkurepa** [comment]
https://github.com/dotnet/arcade-services/pull/3005

**Comment by premun** [comment]
> Currently, when you authenticate on the new, maestro.int-dot.net url, it's trying to use http, because the `locator` variable sees that the cluster is talking to the application gateway via http (we're using https between us, the client and the gateway).

Are you sure that this is actually happening?
The frontend should not be able to tell - the app is running in the browser and the browser calls HTTPS for all it cares.

What do you mean by the `locator`?

**Comment by premun** [comment]
I think the fix should go here:
https://github.com/dotnet/arcade-services/blob/afb827efb0c756a800e3769184be807fc2a1cbdd/src/Maestro/Maestro.Web/Pages/Account/AccountController.cs#L47

**Comment by dkurepa** [comment]
I'll try it out on Staging before creating a PR

**Comment by dkurepa** [comment]
So I tried doing https://dev.azure.com/dnceng/internal/_git/dotnet-arcade-services/commit/76ec44313f8fb4c3b25c80eaa65d71add1b4179d?refName=refs%2Fheads%2Fdkurepa%2FForceHTTPSRedirectUrl, and rolling it out in Staging, it didn't work

**Comment by dkurepa** [comment]
PR: https://github.com/dotnet/arcade-services/pull/3034

**Comment by dkurepa** [comment]
The first PR didn't wasn't enough. We had to create https://github.com/dotnet/arcade-services/pull/3040 to fully resolve the issue.
The github authentication is now using https end to end, so the token handling is safe
