### ISSUE TITLE
Migrate all client code to use the new Application Gateway, plan

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3006]
In https://github.com/dotnet/arcade-services/issues/2783, we will be adding Application Gateway in front of Maestro.
This issue is about writing down a plan to switch all users to use it, instead of the old Load Balancer.

**Comment by dkurepa** [comment]
1. Rollout Maestro, making all of the necessary changes live on production (after the GA)
2. Update arcade scripts and docs, replacing the old url `https://maestro-prod.westus2.cloudapp.azure.com` with the new one `maestro.dot.net`
3. Make sure the arcade updates reach all live repos/branches. A full list can be seen [here](https://microsofteur-my.sharepoint.com/:x:/g/personal/dkurepa_microsoft_com/EQr81jy99RVNnVhPSFGDdrgBoPszOmPZcwCUeX7ztFQTDw?e=C2eaOw)

At this point all of our automation will be migrated to use the new URL. Now we want to make sure that the old url `https://maestro-prod.westus2.cloudapp.azure.com` is still usable, in case someone has custom tooling, or automation:
- Change the DNS label on the public IP address used by the Load Balancer to something other than `https://maestro-prod.westus2.cloudapp.azure.com`
- Set the DNS label on the public IP address used by the Application Gateway to `https://maestro-prod.westus2.cloudapp.azure.com`, create a Listener for it
- Verify the URL works
- Delete the Load Balancer, and it's public IP address

**Comment by dkurepa** [comment]
The plan has been written, we're waiting on the next Maestro rollout before executing it

**Comment by tkapin** [comment]
Was this rolled out already? Anyway, this should be in blocked with clear criteria on when it gets unblocked.

**Comment by dkurepa** [comment]
This issue is in progress, all of the arcade PRs have been merged, and the partner communication has been sent. We're now making sure that all of the arcade updates have flown where they need to

**Comment by dkurepa** [comment]
We found out that there's a few places in the release repo that have the old url hardcoded, issue to deal with it: https://github.com/dotnet/arcade-services/issues/3115

**Comment by dkurepa** [comment]
Followup work https://github.com/dotnet/arcade-services/issues/3123

**Comment by dkurepa** [comment]
All of the client code is now using Application Gateway. We've seen no issues
