### ISSUE TITLE
VMR not sync'd with correct build number of runtime for RC2 release

### ISSUE THREAD

**Issue by mthalman** [dotnet/arcade-services#3010]
The runtime commit for the RC2 release is https://github.com/dotnet/runtime/commit/0b25e38ad32a69cd83ae246104b32449203cc71c.

Here's the builds associated with that:

```
$ darc get-build --commit 0b25e38ad32a69cd83ae246104b32449203cc71c --repo runtime
Repository:    https://dev.azure.com/dnceng/internal/_git/dotnet-runtime
Branch:        refs/heads/internal/release/frameshift/8.0-rc2
Commit:        0b25e38ad32a69cd83ae246104b32449203cc71c
Build Number:  20230929.6
Date Produced: 9/29/2023 5:44 PM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=2280047
AzDO Build Id: 2280047
BAR Build Id:  194966
Released:      False
Channels:
- .NET 8 RC 2
Repository:    https://dev.azure.com/dnceng/internal/_git/dotnet-runtime
Branch:        refs/heads/internal/release/8.0-rc2
Commit:        0b25e38ad32a69cd83ae246104b32449203cc71c
Build Number:  20230926.7
Date Produced: 9/26/2023 6:30 PM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=2276951
AzDO Build Id: 2276951
BAR Build Id:  194404
Released:      False
Channels:
- .NET 8 Internal
Repository:    https://dev.azure.com/dnceng/internal/_git/dotnet-runtime
Branch:        refs/heads/frameshift/internal/release/8.0-rc2
Commit:        0b25e38ad32a69cd83ae246104b32449203cc71c
Build Number:  20230925.17
Date Produced: 9/26/2023 3:27 AM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=2276385
AzDO Build Id: 2276385
BAR Build Id:  194282
Released:      False
Channels:
- .NET 8 RC 2 Internal
```

But the generation of the git info in the VMR associated it with the wrong build number. It associated it with [20230925.17](https://github.com/dotnet/dotnet/blob/1e872358329855089d8d14cec1f06d5b075824b5/prereqs/git-info/runtime.props#L5) instead of the actual build that was used: 20230929.6.

This lead to an issue in source build with version mismatch: https://github.com/dotnet/source-build/issues/3673

If we can't determine what the correct build number is, we need a warning or an error or something to raise awareness. But, I would assume that the newest build is the one that should be used.

**Comment by premun** [comment]
This has been flown to installer via https://github.com/dotnet/installer/pull/17693

@mthalman do we want this in `release/8??`?

**Comment by mthalman** [comment]
> This has been flown to installer via [dotnet/installer#17693](https://github.com/dotnet/installer/pull/17693)
> 
> @mthalman do we want this in `release/8??`?

That's @MichaelSimons call.

**Comment by MichaelSimons** [comment]
> That's @MichaelSimons call.

If there is any chance of this issue occurring in .NET 8.0 then it should be backported IMO.

Regardless if this particular change is backported or not, I thought we only have one arcade-services branch in support across all servicing releases?  If so isn't it best to keep all servicing branches up-to-date?  If there ever is a bug fix/CVE needed you would have to take a big version jump which feels risky in itself.

**Comment by premun** [comment]
I'd definitely backport, I was rather more wary of committing into the `8.0` branches at this time because I don't fully understand if it will affect any last minute changes etc to the GA build.

Or we're good and we can start committing into `8.0.1xx` again?

**Comment by premun** [comment]
Okay, so this is in all installer branches already. We have an E2E tests covering this scenario in the VMR tooling too. Closing
