### ISSUE TITLE
[Darc/Maestro++] Add validation for the swagger website during deployment

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade-services#3018]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As https://github.com/dotnet/arcade/issues/8064 shows, we had a change go through PR and official build validation that broke the swagger definition for the 2020-02-20 API.

We should look into ways to validate this won't be broken as early as possible.

**Comment by premun** [comment]
This is no longer relevant
