### ISSUE TITLE
Maestro is deleting feeds it shouldn't

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3041]
Recently, we've been seeing a few cases where Maestro has been deleting feeds it shouldn't, breaking the dependency flow builds.
An example of this is:
- https://github.com/dotnet/r9-samples/pull/131/commits/5f4818a74e2b0db80ffd442c823cc2f9d2dbc75e

This is a bug that's slowing us down, and requiring manual intervention. We should fix it

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description
Maestro shouldn't delete feeds that are needed for builds

**Comment by RussKie** [comment]
This issue is persistent:
* https://github.com/dotnet/r9-samples/pull/132
* https://github.com/dotnet/r9-samples/pull/136

**Comment by mmitche** [comment]
@RussKie Actually, no, Maestro is doing what is correct here. Extensions has a dependency on assets from runtime at sha c88b3776d0fb3bb33fcd4192b476147c0895bd6f. 

```
    <Dependency Name="Microsoft.Extensions.Hosting" Version="8.0.0">
      <Uri>https://github.com/dotnet/runtime</Uri>
      <Sha>c88b3776d0fb3bb33fcd4192b476147c0895bd6f</Sha>
    </Dependency>
```

This appears to be a stable build of runtime that was produced around June 29th. This is likely a test stable build. It never produced an asset called `Microsoft.Extensions.Hosting` at `8.0.0`. Thus, the feed setup you have manually added is incorrect. Either the sha of the asset, or the input feed are incorrect.

```
PS C:\r\source-build> darc get-asset --name Microsoft.Extensions.Hosting --version 8.0.0 --max-age 180 | findstr c88b3776d0fb3bb33fcd4192b476147c0895bd6f
PS C:\r\source-build>
```

**Comment by RussKie** [comment]
As @mmitche pointed, the issue was caused by an incorrect sha. Having corrected the sha, the maestro added the required feed, and everything worked.

Thank you for your time.

**Comment by RussKie** [comment]
Feel free to close as I don't have permissions to do so.
