### ISSUE TITLE
(Re-)setup Maestro++ for the dotnet/extensions-samples repository

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#3087]
Discussion: [in Teams](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1700618161371?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1700618161371&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1700618161371)

The dotnet/r9-samples repository was renamed to dotnet/extensions-samples and the customer gets an error while trying to create a subscription:
> fail: Failed to create subscription: {"message":"the request is invalid","errors":["The repository 'https://github.com/dotnet/extensions-samples' does not have an associated github installation. The Maestro github application must be installed by the repository's owner and given access to the repository."]}

1. Do we have a bug in Maestro++? do not process event (the repo was renamed) from GH
2. Try to mitigate by preparing data change script and modify BAR DB.
3. Document steps.

## Docs:
- https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/1009/Accessing-the-BAR-(BuildAssetRegistry)-database

## Follow up:
- https://github.com/dotnet/arcade-services/issues/3088
- https://github.com/dotnet/dnceng/issues/1479

**Comment by dkurepa** [comment]
To give some more information on this issue, basically we have a line in the `Repositories` table in the bar that says `dotnet/r9-samples, <gh app installation id>`. Even tho the repository was renamed, this line still stayed, to fix the issue above, we need to add a line for `https://github.com/dotnet/extensions-samples`, we can do that in two ways:
 - edit the original line by changing the repo name
 - Uninstall and install the Maestro GH app again, and then remove the old line

And then, as a follow up add a listener to the GitHub Repository event to handle the renaming, as Andrii mentioned above

**Comment by premun** [comment]
Should we maybe create a Maestro endpoint that would do the rename in the DB? This seems to come back

**Comment by dkurepa** [comment]
Yes, we have a follow up issue for that

**Comment by mmitche** [comment]
Only the repositories table is critical. The rest of the items (subscriptions, policies), could be recreated manually

**Comment by andriipatsula** [comment]
> Only the repositories table is critical. The rest of the items (subscriptions, policies), could be recreated manually

Ok, I'll run an update query on the `Repositories` table, restart the Maestro service and notify customer.

**Comment by RussKie** [comment]
Are we there yet? :)

**Comment by andriipatsula** [comment]
closing this one as resolved.
