### ISSUE TITLE
Maestro flow branch compare links not working

### ISSUE THREAD

**Issue by garath** [dotnet/arcade-services#3114]
Customer reports [in the FR channel](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1701816754075?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1701816754075&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1701816754075) that Maestro's dependency flow PR for https://github.com/dotnet/runtime/pull/95554#issue-2022511022 contain apparently invalid links for the UI to compare changes. 

For example, the line

```
optimization.linux-arm64.MIBC.Runtime: [from 1.0.0-prerelease.23580.3 to 1.0.0-prerelease.23602.3](https://dev.azure.com/dnceng/internal/_git/dotnet-optimization/branches?baseVersion=GCb86eff9a62&targetVersion=GC9ecde9217b&_a=files)
```

shows a UI complaining that "No commits were found that matched the specified criteria." 

However, using the full hash instead of an abbreviated hash gets the desired results:

```
optimization.linux-arm64.MIBC.Runtime: [from 1.0.0-prerelease.23580.3 to 1.0.0-prerelease.23602.3](https://dev.azure.com/dnceng/internal/_git/dotnet-optimization/branches?baseVersion=GCb86eff9a62fcd19839f0273d1aa1570b8dec6a48&targetVersion=GC9ecde9217bbd3541f1a9dc2d684b9acfa5f27274&_a=files)
```

**Comment by dkurepa** [comment]
AzDo doesn't support short shas for commit comparison, we'll have to go full URL. Before merging the PR I'd like to check what happens if you try to open a PR with more than 5k characters

**Comment by tkapin** [comment]
Why is not the PR merged yet? Is there something blocking it?

**Comment by dkurepa** [comment]
The PR has been merged. We are now using full shas for the comparison urls. If a PR description is too long, we cut it to fit the 5k character limit. In the future, we might consider adding some kind of message for the users, if we  get some complaints
