### ISSUE TITLE
Maestro Load Balancer cleanup

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3123]
After #3117 is done, all of the Maestro traffic will go through the Application Gateway.
We will then be able to clean up the Load Balancer resources in two steps:
 - Stop the Maestro API from listening on port 4430, and close it in the cluster settings

After this is done, we will wait for some time (1-2 months) to make sure everything is working as expected.
If something does go wrong, we will easily be able to go back to the old state by reverting the PR and deploying

- Delete the Load Balancer and the Public IP Address it's using

**Comment by dkurepa** [comment]
We have closed down the port 4430, this concludes the first phase of the cleanup.
We will now wait for a month or two before removing the Load Balancer, so we're 100% sure we don't need it

**Comment by tkapin** [comment]
We shouldn't delete the LoadBalancer until #3131 is solved as the Load Balancer might be needed to connect to the Service Fabric Explorer. Toi minimize the security risk, the Load Balancer should be set up the same way as is for Helix.

**Comment by dkurepa** [comment]
Maestro is getting decommissioned, so this is no longer applicable
