### ISSUE TITLE
Create a Production environment for the service and make deployments possible

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3183]
Once we have the final shape of the Product Construction Service, we should create a Production environment for it. The environment should be created with the bicep script we're writing.

The other important piece of this issue is to create a deployment pipeline for it. In this pipeline, we will want to deploy an image that's already been built, and tested in the staging environment

**Comment by premun** [comment]
Succeeded by https://github.com/dotnet/arcade-services/milestone/41
