### ISSUE TITLE
Maestro++ lost track of a dependency update PR

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#3192]
Dependency update PR: https://github.com/dotnet/arcade/pull/14343

Maestro++ is not updating the merge policy check even after all other checks have succeeded. It still says "Unsuccessful checks: 2" https://github.com/dotnet/arcade/pull/14343/checks?check_run_id=20261521729, even if all checks are green.

The only logs available are traces:
```Kusto
exceptions
| where timestamp > now()-7d
| where * has "dotnet/arcade/pull/14343" or * has "7b33cc16-e98e-4863-7919-08d8e262a02c"

traces
| where timestamp > now()-7d
| where * has "dotnet/arcade/pull/14343" or * has "7b33cc16-e98e-4863-7919-08d8e262a02c"
```

> 1/8/2024, 1:16:29.127 PM
Actor activated. Actor type: SubscriptionActor, actor ID: 7b33cc16-e98e-4863-7919-08d8e262a02c
Adding dependency flow event for 7b33cc16-e98e-4863-7919-08d8e262a02c with Fired New PR
Adding dependency flow event for 7b33cc16-e98e-4863-7919-08d8e262a02c with Created New PR
Asset update complete for 7b33cc16-e98e-4863-7919-08d8e262a02c
Actor deactivated. Actor type: SubscriptionActor, actor ID: 7b33cc16-e98e-4863-7919-08d8e262a02c

And by design Maestro++ must check PR every 5 mins for mergeability.

### Release Note Category
- [ ] Feature changes/additions 
- [x] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by premun** [comment]
I believe this can be closed? We did a bunch of fixes in this area since it was reported.

**Comment by andriipatsula** [comment]
Yeh. Let's close this one. We have not had such issues for a while. We can always reopen it again. Thanks.
