### ISSUE TITLE
`arcade-services`, `dotnet-release` AzDO work items should mirror in `arcade-services`, not `dnceng`

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3205]
Currently, we have some automation that mirrors our AzDo workitems in GitHub issues like so https://github.com/dotnet/dnceng/issues/1782. The issue is that it opens up arcade-services issues in the dnceng repo. We should change that and have it open up issues in arcade-services

**Comment by premun** [comment]
This is done now
