### ISSUE TITLE
dotnet/release Schedule-Validation-Pipeline is broken

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade-services#3237]
https://dev.azure.com/dnceng/internal/_build?definitionId=829

The pipeline is responsible for triggering the Validate-Dotnet pipelines for each product repo.

- [ ] Setup monitoring (email notification) to notify the team that the pipeline is broken.

[build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2362551&view=logs&j=559e8c61-8d51-558d-7b08-43d2f6c6578c&t=67a4272e-b412-5521-fd1f-95beadaad539&l=427)

The problem was caused by a recent commit: [f6ec58def4f336d5ef562d8ef7997310c7c9eb33](https://dev.azure.com/dnceng/internal/_git/dotnet-release/commit/f6ec58def4f336d5ef562d8ef7997310c7c9eb33?refName=refs/heads/apatsula/test_darclib_version&path=/validation-pipeline.yml) (Splitting of the Staging pipeline)

Several parameters were missing.
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/36881

**Comment by andriipatsula** [comment]
Follow up: https://github.com/dotnet/arcade-services/issues/3243

**Comment by andriipatsula** [comment]
The issue is resolved. The https://dev.azure.com/dnceng/internal/_build?definitionId=827&_a=summary pipeline is running.
I am not closing this issue as we still need to "Setup monitoring (email notification) to notify the team that the pipeline is broken."

**Comment by premun** [comment]
@andriipatsula can you set up the notification if it's still needed?

**Comment by andriipatsula** [comment]
Notification created for both Validate-DotNet and Schedule-Validation-Pipeline pipelines. closing as resolved.
