### ISSUE TITLE
Aspire workload should be pinned to the same version as `Aspire.Hosting`

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3242]
Recently Aspire was updated, and our CI started failing because the version of the Packages we use diverged from the workload. We want to pin the workload version to the one that's in Directory.Packages.Props

**Comment by dkurepa** [comment]
We mitigated this issue by commenting out the Aspire code that was causing the build error. This is just a band aid solution, we should come up with a permanent one

**Comment by premun** [comment]
@dkurepa I need to remove the feed specification to unblock an urgent darc fix

**Comment by dkurepa** [comment]
yeah, let's do that and comment out the aspire App.Host to unblock this

**Comment by dkurepa** [comment]
The PR has been merged. From now on, we will follow the latest available aspire preview
