### ISSUE TITLE
Eliminate the `useServicingBuildPool` parameter to promotion pipeline

### ISSUE THREAD

**Issue by dougbu** [dotnet/arcade-services#3258]
once dotnet/dnceng#1145 and dotnet/arcade#14445 fixes roll out (hopefully tomorrow), passing the `useServicingBuildPool` parameter to the `Maestro Build Promotion` pipeline will either do nothing or result in an error for all publishing attempts in servicing branches. need to eliminate the following to ensure servicing continues smoothly.

https://github.com/dotnet/arcade-services/blob/2a734cad5b603ea6b6f67a309cbaa081af57cf77/src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs#L269-L273

this amounts to reverting the changes made in #2000

if the code won't cause an error, this fix becomes minor clean-up and could be postponed

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements

### Release Note Description

Removed an eliminated parameter when submitting jobs to the `Maestro Build Promotion` pipeline in dnceng/internal. Please run eng/common/darc-init.sh or eng/common/darc-init.ps1 after the rollout completes to ensure `darc add-build-to-channel` operates correctly. Other `darc` commands were unaffected.

See dotnet/arcade#14445 for the breaking change this reacts to.

**Comment by dougbu** [comment]
@dotnet/dnceng I couldn't find an `Ops - Service Maintenance` label in this repo for this issue (or maybe #3259). if this lack matters, let me know and suggest either an alternative (existing if one's available) label or duplicating `Ops - Service Maintenance` from dotnet/arcade and dotnet/dnceng.

**Comment by oleksandr-didyk** [comment]
Rolled out by https://github.com/dotnet/arcade-services/issues/3264
