### ISSUE TITLE
Investigate potential silent failure in Arcade update logic

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade-services#3276]
Discovered by https://github.com/dotnet/arcade-services/pull/3274

The PR linked above fixes a potential NRE inside logic responsible for updating Arcade. This failure was caught by the [`ArcadeSdkUpdate`](https://github.com/dotnet/arcade-services/blob/a81c4da120ea8d538568a03bb14f4476ea67dbf6/test/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs#L31) test consistently, but has not produced any visible exceptions or failures in the service logs, masking the issue and making it far harder to uncover the reason behind the test failing.

We should investigate why was this issue not instantly visible to us from monitoring or logging.

**Comment by premun** [comment]
I think this is resolved, it was about the remote factory
