### ISSUE TITLE
Local update-dependencies broken for arcade updates

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#3295]
This change https://github.com/dotnet/arcade-services/commit/40ea8783ac779ea6ee1772c92b52976ec9c88863#diff-c1246df561b77ff309db7e9a66bb8e14b13eb56120b64130953ed65962faac08L79-R77 in https://github.com/dotnet/arcade-services/pull/3256 stopped using the remote to look up the arcade global json information. Instead, it uses the local git client, which won't work since it needs to get the file content from the remote git repository.

Repro is:

`darc update-dependencies --id 212247`

on any arcade-ified repo.

**Comment by mmitche** [comment]
@premun

**Comment by garath** [comment]
Conversation on this is also happening in dotnet/dnceng#2002

**Comment by MilenaHristova** [comment]
Rolled out with https://github.com/dotnet/arcade-services/issues/3288
