### ISSUE TITLE
Remove release packages layout creation from gather-drop

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#3334]
Epic: https://github.com/dotnet/release/issues/740

Remove the release packages layout creation from gather-drop. The layout creation is moved to the release infra with https://github.com/dotnet/release/issues/828
Don't copy packages into folders, the output of gather-drop should be 2 folders - `Shipping` and `NonShipping` and a file `manifest.json`

Previous output layout of gather-drop:
```
├── manifest.json
├── shipping/
│   ├── assets/  
│   └── packages/  
├── nonshipping/
│   ├── assets/  
│   └── packages/  
└── publish_files/
    └── nuget/
        ├── identities/
        |   ├── aspnetcore.csv
        |   ├── efcore.csv
        |   ├── emsdk.csv
        |   ├── linker.csv
        |   ├── runtime.csv
        |   ├── sdk.csv
        |   ├── templating.csv
        |   └── windowsdesktop.csv
        ├── nukgs-all-just-for-reference.txt
        ├── nukgs-aspnet.txt
        ├── nukgs-core.txt
        ├── sympkgs-all.txt
        ├── nupkgs/
        └── sympkgs/
```
New output layout:
```
├── manifest.json
├── shipping/
│   ├── assets/  
│   └── packages/  
└── nonshipping/
     ├── assets/  
     └── packages/  
```
### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description
Removed release packages layout creation from gather-drop

**Comment by MilenaHristova** [comment]
There are 2 changes in `gather-drop` that are part of this
- removing the [CreateReleasePackagesLayout](https://github.com/dotnet/arcade-services/blob/a688e34a3c0551eafd9c2ab8b06a3b88faf4141c/src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs#L440) function
  - we can either remove this completely or keep it behind a option like `--create-release-packages-layout` 
  - we should make sure no one except the release infra relies on the layout 
- replacing the list of targets from the `manifest.json` assets with a single target - in [GetTargetPaths](https://github.com/dotnet/arcade-services/blob/a688e34a3c0551eafd9c2ab8b06a3b88faf4141c/src/Microsoft.DotNet.Darc/DarcLib/Helpers/ManifestHelper.cs#L97)
  - the first target location is the "release packages layout" location
  - it's used only to copy files to that layout
  - in general it's confusing that we have 2 targets as a list and it's not clear which is used for what

**Comment by MilenaHristova** [comment]
PR: https://github.com/dotnet/arcade-services/pull/3495

I didn't find any use of `publish_files` folder in dotnet org on GitHub but to be sure @mmitche, do you know if anyone uses gather-drop apart from the release infra ?

**Comment by mmitche** [comment]
Nothing that I know of. And if they use it, then not `publish_files`

**Comment by MilenaHristova** [comment]
PR for the documentation: https://github.com/dotnet/arcade/pull/14762

**Comment by MilenaHristova** [comment]
This is done with https://github.com/dotnet/arcade-services/pull/3495
