### ISSUE TITLE
Initialize GitHubAuthenticationOptions and pass them to `ConfigureAuthServices`

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3351]
We're currently getting the `GitHubAuthentication` Configuration section and passing it around to ConfigureAuthServices after injecting secrets. It'd be nicer if we could just Initialize the GitHubAuthenticationOptions and pass it.

We tried this briefly, but configuration wasn't properly resolving in some Auth libraries

**Comment by premun** [comment]
This one is no longer needed, we don't have GitHub auth anymore
