### ISSUE TITLE
Add `TargetDirectory` field to subscriptions

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#3368]
### Context 

We will need a target directory field for 2 purposes:

1. For code flow subscriptions, we will use the source/target directory fields to tell whether a subscription is to/from the VMR.
2. For regular subscriptions, we will allow targeting a repo folder in the VMR using this.

### Goals

- Extend the model and incorporate this into the pop-ups in darc.
    - Do not allow both source and target to be set.
    - Do not allow source to be set for non-code-flow subscriptions.
    - Require exactly one to be set for code-flow subscriptions.

**Comment by oleksandr-didyk** [comment]
Rolled out by https://github.com/dotnet/arcade-services/pull/3476
