### ISSUE TITLE
Migrate arcade-services pipeline to 1ES templates

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/arcade-services#3396]
Tracking issue for migrating `arcade-services` pipeline to 1ES templates

**Comment by oleksandr-didyk** [comment]
After we migrate the pipeline, we need to also add the auto-generated baseline to the repo without breaking the internal mirroring. For this, we need to:
  - wait for the migrated pipeline to get mirrored internally and for a build to pass
  - wait for 1ES bot to open a PR adding the baseline
  - cherry-pick the commit from the PR and add it to GitHub
  - abandon the bot's PR
  - wait for the baseline to get mirrored internally
 
These manual steps are required or we will break the mirroring for the repo

**Comment by garath** [comment]
Let me know if you need any help getting any arcade-services production pipelines into compliance with 1ES Pipeline Templates.

**Comment by oleksandr-didyk** [comment]
Expected warnings related to the baseline seem to be gone, there is still an SBOM failure, but it should be fixed by https://github.com/dotnet/arcade/issues/14560

Waiting for it to flow into `arcade-services` and get mirrored

**Comment by oleksandr-didyk** [comment]
Update was merged and mirrored, build is green with no warning / errors. Closing
