### ISSUE TITLE
Add a Maestro exception panel to Grafana

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3427]
We want to add a Maestro Exception grafana panel
### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Add Maestro Exception Grafana panel

**Comment by dkurepa** [comment]
The PR adding the new panel has been merged. Waiting for the dnceng staging rollout to verify everything works

**Comment by premun** [comment]
@dkurepa can this be closed?

**Comment by dkurepa** [comment]
The panel was added in this PR https://github.com/dotnet/dnceng/pull/2309
