### ISSUE TITLE
VMR Syncronization Pipeline failing for 9.0.1xx-preview3

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/arcade-services#3433]
The dotnet-dotnet-synchronization pipeline attempted to run on Monday 3/18 for the preview3 branch. However, the pipeline failed with the following error:

```
The pipeline is not valid. Could not get the latest source version for repository dotnet/dotnet hosted on https://github.com/ using ref refs/heads/release/9.0.1xx-preview3. GitHub reported the error, "No commit found for SHA: refs/heads/release/9.0.1xx-preview3"
```

The github 9.0.1xx-preview3 branch had commits as of Monday (and continues to have commits).

[Link to failing run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2407621&view=results)

cc @premun

**Comment by premun** [comment]
This can be that whoever is snapping installer doesn't create the VMR branch in time. We can run a new build or we can just wait for a new commit in that branch of installer.

I queued a new build which can find the branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=2410448&view=results
