### ISSUE TITLE
Streamline the dnceng / prodconsvcs GitHub teams

### ISSUE THREAD

**Issue by tkapin** [dotnet/arcade-services#3633]
Currently, the Product Construction Services team is part of the [dnceng](https://github.com/orgs/dotnet/teams/dnceng) team on GitHub, which results in the team getting notifications that are not relevant to it.

The historical reason for sharing one GH team was it used to be one of the FR channels, but @ilyas1974  confirmed that it's used very infrequently by customers with no SLA associated with it.

The [prodconsvcs](https://github.com/orgs/dotnet/teams/prodconsvcs) GH team should be used for team-wide notifications instead.

**The goals of this issue** are:
* [x] Remove the PCS team members from the  [dnceng](https://github.com/orgs/dotnet/teams/dnceng) GH team
* [ ] Add the [prodconsvcs](https://github.com/orgs/dotnet/teams/prodconsvcs) GH team as recipients of the Grafana alerts

### Release Note Description
don't include in release notes

**Comment by tkapin** [comment]
Removed the PCS team members from the `dnceng` GH team, verified with @premun that the team doesn't lose access to any repos because of that.

**Comment by tkapin** [comment]
@dkurepa - can you please take care of adding the Add the [prodconsvcs](https://github.com/orgs/dotnet/teams/prodconsvcs) GH team as recipients of the Grafana alerts? Thanks

**Comment by dkurepa** [comment]
PR: https://github.com/dotnet/dnceng/pull/3075/files

**Comment by premun** [comment]
This is done now
