### ISSUE TITLE
scenario tests failing to login with federated token

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#3700]
build https://dev.azure.com/dnceng/internal/_build/results?buildId=2486160&view=results

```
ERROR: Decryption failed: [WinError -2146893813] Key not valid for use in specified state. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231
```

we will add continue on error to this step to unblock the rollout

**Comment by MilenaHristova** [comment]
looks like it's a bug in `az login` https://github.com/Azure/azure-cli/issues/20231

**Comment by premun** [comment]
@MilenaHristova this seems fixed now?

**Comment by MilenaHristova** [comment]
> @MilenaHristova this seems fixed now?

did it get fixed in azure cli?

**Comment by MilenaHristova** [comment]
`az login` is working fine in recent builds, closing as resolved
