### ISSUE TITLE
Refactor Darc to properly use DI

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3745]
Darc dependency injection is currently messy, and we keep breaking it while developing because we're currently not able to have proper test coverage for the DI.
We should refactor it, and then add `DependencyRegistrationTests` like we do for all other projects

**Comment by premun** [comment]
@dkurepa somehow the DI test is hanging in CI but goes green locally. I didn't have time to fix this but I finished your PR and merged it without it.

**Comment by dkurepa** [comment]
I'll close this issue now. I created a followup and included the DI registration test in it https://github.com/dotnet/arcade-services/issues/3785
