### ISSUE TITLE
Revert arcade workaround, and double check which operations support json

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3785]
In https://github.com/dotnet/arcade-services/issues/3745, we refactored quite a bit of darc, and made a mistake, an operation that used to support json was refactored not to support it which caused an error in the publishing pipeline. To hotfix this, we pinned the darc version to an older one https://github.com/dotnet/arcade/pull/14987.

We merged the fix for this, but want to double check if there's any other places we missed https://github.com/dotnet/arcade-services/pull/3784.
We should also fix and enable the DI registration test

**Comment by dkurepa** [comment]
I double checked, after yesterdays PR all operations that supported json output still support it. We should rollout out now, and revert the arcade PR

**Comment by premun** [comment]
@dkurepa what is the status of this? Have we reverted the PR correctly?

**Comment by dkurepa** [comment]
We didn't revert it, we improved the pipeline by adding a darc version variable that we can set in case we need to pin to a specific version, there was a different issue for it https://github.com/dotnet/arcade-services/issues/3798. Closing this now
