### ISSUE TITLE
Add Production Environment

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3799]
Most of these issues are described in https://github.com/dotnet/arcade-services/milestone/39.
This mainly includes:
 - Creating all Azure Resources in the production subscription (using the bicep script)
 - Creating all needed Service Connections
 - Changing the CI to release already built and tested containers, from the Staging environment
 - Configuring E2E tests to work with the new infra

**Comment by premun** [comment]
As an example, this is a service ticket opened for INT PCS MI to be added to DevDiv:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2221593

A new one can be opened here: https://aka.ms/vsengticket

**Comment by dkurepa** [comment]
We'll also have to add a few Managed Identities to the AzDo project:
- ProductConstructionProd (needs to have the same permissions as Maestro)
- FeedCleanerProd (needs to be added to https://dev.azure.com/dnceng/internal/_settings/permissions?subjectDescriptor=vssgp.Uy0xLTktMTU1MTM3NDI0NS0xMzQ5MTQwMDAyLTIxOTY4MTQ0MDItMjg5OTA2NDYyMS0zNzgyNDgyMDk3LTEtMjMzNTMyMDA4Ny0zMDMyNTUyNzcyLTMxNTMyMDE5NTgtMTgyNTMxMTU2MQ)

**Comment by premun** [comment]
We will also need to tell Will Thant that the MI needs to be added to their WindowsAppSDK AzDO orgs

**Comment by dkurepa** [comment]
We successfully created the prod environment using the bicep script and other steps in the readme.
There's a bit of follow-up work with giving permissions to container jobs

**Comment by dkurepa** [comment]
The ICM has been resolved, and PCS can now has access to DevDiv https://dev.azure.com/devdiv/DevDiv/_git/vs-code-coverage/pullrequest/588730

**Comment by dkurepa** [comment]
@premun any updates on the WindowsSDK AzDo org?

**Comment by premun** [comment]
They will set it up and you can consider it done

**Comment by dkurepa** [comment]
thanks!
