### ISSUE TITLE
Port SubscriptionActorService

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade-services#3807]
This issue depends on #3805. We'll need to:
 - Replace the code using SF Actor memory with Redis
 - Try to remove the reflection that's currently being used in the code
 - Keep the same entrypoints (these can currently be called by the API, the DependencyUpdater, from a Reminder)
 - This is a critical part of the infrastructure, so we'll port all unit tests, and improve them if needed
 - Check if we need error handling, port if needed (we currently have a mechanism that logs failed attempts and retries them late)
 - Add Metrics to measure actor actions

We need to make sure that we don't change any logic of the actual actor, since it has many edge cases that we've discovered during the years. We only want to change how the logic is being run, from SF actors, to PCS Jobs

**Comment by premun** [comment]
List of follow-ups:
- Move subscription actor ID out of ctor and into method calls
- Make codeflow logic run right away and not async via a queue message

**Comment by premun** [comment]
Ok, the actors have been ported to PCS. I will keep this opened for some additional changes and fixes we will need. Things have not been tested, just through the unit tests

**Comment by premun** [comment]
Ok closing this one, will open new ones for the respective failures/bugs
