### ISSUE TITLE
Incorrect commit comparison links created

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/arcade-services#3944]
It looks like when the bot updates PR comments with new commit information it takes the previous incoming commit sha and uses that as the new "starting" commit sha instead of preserving the real starting commit sha.

See https://github.com/dotnet/aspnetcore/pull/57742 for example. It currently links to https://github.com/dotnet/runtime/compare/c4792a228e...39c84a3a1b but it should be https://github.com/dotnet/runtime/compare/ce8f49e658...39c84a3a1b.

**Comment by premun** [comment]
Thanks for reporting, we will have a look

**Comment by premun** [comment]
Re-opening as it was not rolled out yet

**Comment by oleksandr-didyk** [comment]
Rolled-out in https://github.com/dotnet/arcade-services/releases/tag/v20241029.2-1.1.0-beta.24529.2
