### ISSUE TITLE
Diff links show incorrect diff

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#4010]
The diff links appear to show the incorrect diff now, if multiple updates to a PR were made. It looks like only the latest diff is shown, rather than the diff from the original dependency version to the new version.

e.g. https://github.com/dotnet/aspnetcore/pull/58090

**Comment by oleksandr-didyk** [comment]
This seems to be duplicate of https://github.com/dotnet/arcade-services/issues/3944

**Comment by mmitche** [comment]
Closed as dupe
