### ISSUE TITLE
[BarViz] Dependency tree showing weird entries

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#4046]
https://product-construction-prod.wittysky-0c79e3cc.westus2.azurecontainerapps.io/channel/5173/github:dotnet:sdk/build/latest

![Image](https://github.com/user-attachments/assets/af242611-32d1-43e2-977d-7274dbb525e6)

A core-setup build from 2019 shouldn't show up in sdk for .NET 10.

**Comment by oleksandr-didyk** [comment]
The entries in the dependency tree are just builds coming from the `dependencies` section of a given build in BAR. Those, in turn, are builds for the version references in `Version.Details.xml` of a given repository

SDK does have a [reference](https://github.com/dotnet/sdk/blob/f542dd4ea220971012db09c80b8e86016210e95d/eng/Version.Details.xml#L63) to the specific `core-setup` build, so this view is correct
