### ISSUE TITLE
[BarViz] Build page does not show channel name

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#4047]
When you are given an url and go directly to it, e.g. https://product-construction-prod.wittysky-0c79e3cc.westus2.azurecontainerapps.io/channel/5173/github:dotnet:sdk/build/latest, it is unclear which channel this belongs to because:
- The left tree does not expand to it
- The URL only contains channel ID
- The page does not contain a header with this information

**Comment by oleksandr-didyk** [comment]
Rolled out by https://github.com/dotnet/arcade-services/releases/tag/v20241029.2-1.1.0-beta.24529.2
