### ISSUE TITLE
Make sure GitHub app installation events/webhooks are working

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#4066]
This is something that used to work in Maestro and we might need to either change the DNS to hit PCS correctly or also check if we have the right endpoints in the first place.

**Comment by premun** [comment]
Related: https://github.com/dotnet/arcade-services/issues/3527

**Comment by dkurepa** [comment]
When we're switching from Maestro to PCS as the only service, we'll also have to update the Maestro production GH application. I'll write that in that issue too

**Comment by dkurepa** [comment]
One thing I had to do for this issue is to copy the WebHooks Secret from maestroint to the PCS staging KV. The app can only have one secret at a time, and the Secret Manager just creates an empty secret for us. I'll do that for prod to so it's ready when we do migrate
