### ISSUE TITLE
Propagate build info to git-info files

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#4165]
## Context

The information in the https://github.com/dotnet/dotnet/tree/main/prereqs/git-info files (and in the `source-manifest.json`) contain package versions associated with the SHAs that are synchronized into the repository.
Right now, this info comes from the `Version.Details.xml` files of product repos.
Eventually, this will not be needed anymore but for now we do need those so that we can build the same versions of packages in Source Build as the Microsoft build.

## Goal

For codeflow subscriptions, these files will still need to be updated but the information must come from the build that is being flown.

**Comment by dkurepa** [comment]
This issue is completed
