### ISSUE TITLE
Include build ID in last flow information

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#4166]
## Context

When we flow code between VMR and repos, we store the SHA we were flowing:
- From repo to VMR, we store the `source-manifest.json`
- From VMR to repo, we store it in `Version.Details.xml`

However, since we now flow builds, those also include package updates (build assets).
When the code flow algorithm meets a conflict (shown [here](https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/VMR-Full-Code-Flow.md#conflicts)), we need to reconstruct a previous flow from the previous checkpoint. But for this, we also need the build ID so that we can also reconstruct the package updates.

## Goal

Store BAR build ID in the version files when flowing builds so that previous flows can be reconstructed.

I am not sure what to do with excluded assets as those are stored on the subscription and we won't have access to those but I guess it's fine.

**Comment by dkurepa** [comment]
This issue should be done now, with the two PRs above
