### ISSUE TITLE
Enable prod stable version generation and tagging

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade-services#59]
I've disabled this for now to unblock a prod rollout.  Stable versions cannot be generated because of prerelease Microsoft.TeamFoundationServer.Client dependencies.

**Comment by markwilkie** [comment]
@mmitche What is the next step?

**Comment by mmitche** [comment]
Waiting for a stable version of Microsoft.TeamFoundationServer.Client that we can depend on. This is not critical work.
