### ISSUE TITLE
Is buliding on Linux supported?

### ISSUE THREAD

**Issue by omajid** [dotnet/arcade-services#602]
I am trying to build this on Linux x86_64. There's a number of issues, such as #494, that make me suspect that this will not work on Linux at all.

Is Linux known to work (or not to work)? Should I try and continue trying to build this on Linux or should I just assume this is a Windows-only component?

**Comment by alexperovich** [comment]
Because this is a windows service fabric app it requires things that come with visual studio and are windows only. It is not expected to work on linux.

**Comment by omajid** [comment]
Thanks. Parts of this end up getting used on Linux and FreeBSD via source-build (eg https://github.com/dotnet/source-build/issues/1139#issuecomment-520310058) and I was interested in building those pieces myself.

**Comment by alexperovich** [comment]
It should be possible to build most of the projects on linux. The majority of them are just .net core library/console apps. Building the whole tree will fail on the *.sfproj though because it references targets from the VS install.
