### ISSUE TITLE
Consume the goal artifact from arcade

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade-services#721]
Consume the goal artifact from Arcade, parse it and then ingest into kusto

- [ ]  Parse the file  
- [ ] Ingest into kusto into the TimelineBuild table.

**Comment by riarenas** [comment]
@epananth should this issue be moved to Arcade?

**Comment by epananth** [comment]
Issue moved to [dotnet/arcade #4217](https://github.com/dotnet/arcade/issues/4217) via [**ZenHub**](https://www.zenhub.com/)
